export const JAVASCRIPT = {
    name: "JavaScript",
    palette: ["#f7df1e", "#f97316"],
    kw: "javascript,code",
    images: ["1627398242454-45a1465c2479", "1593720213428-28a5b9e94613", "1579468118864-1b9ea3c0db4a"],
    levels: {
        Basic: [
            {
                t: "JavaScript Fundamentals: Values, Variables, and Types", s: "js-fundamentals",
                e: "The language of the web, from zero: where JS runs, how to declare variables, and the types underneath everything.",
                sec: [
                    ["Where JavaScript runs", "JavaScript executes in two main places: every browser (open DevTools with F12 and try the Console tab right now) and Node.js on servers. The same language powers interactive pages, APIs, mobile apps, and desktop software — which is why it's consistently the world's most-used language."],
                    ["let, const, and types", "Declare with const by default and let only when reassignment is needed — var is legacy, avoid it. Core types: string, number (one type for integers and decimals), boolean, null, undefined, and object. typeof reveals what you're holding.", 'const name = "Asha";\nlet score = 41.5;\nconst active = true;\nconsole.log(typeof name, typeof score, typeof active);\n// string number boolean'],
                    ["Template literals and basic operators", "Backtick strings embed expressions with ${...} and span multiple lines — use them everywhere. Know the equality trap: === compares value AND type (always use it); == coerces types and causes classic bugs like 0 == '' being true.", 'const user = "Ravi";\nconst msg = `Welcome back, ${user}!\\nYou have ${2 + 3} alerts.`;\nconsole.log(msg);\nconsole.log(0 === "");   // false — always use ===`'],
                ],
                ex: "In the browser console, create const variables for your name and city and a let for visit count. Print a template-literal sentence using all three, increment the count, and print it again.",
                tips: ["const by default, let when reassigning, never var", "Always compare with ===", "Backtick strings with ${} are the modern default"],
            },
            {
                t: "Functions, Arrays, and Objects", s: "js-functions-arrays-objects",
                e: "The building blocks of every JavaScript program — and the array methods you'll use daily for the rest of your career.",
                sec: [
                    ["Functions three ways", "Function declarations, function expressions, and arrow functions all create callable logic. Arrows are the modern default for short functions and callbacks; their concise form returns automatically without braces.", 'function add(a, b) { return a + b; }\nconst subtract = function (a, b) { return a - b; };\nconst multiply = (a, b) => a * b;\nconsole.log(add(2, 3), subtract(5, 2), multiply(4, 2));'],
                    ["Arrays and the big three methods", "map transforms every element, filter keeps some, reduce boils the array to one value. These three replace most loops and read as intent instead of mechanics — mastering them is the single biggest jump in JS fluency.", 'const prices = [120, 45, 99, 300];\nconst withTax = prices.map(p => p * 1.18);\nconst affordable = prices.filter(p => p < 100);\nconst total = prices.reduce((sum, p) => sum + p, 0);\nconsole.log(withTax, affordable, total);'],
                    ["Objects and destructuring", "Objects group labeled values; destructuring pulls fields out into variables in one line, and the spread operator copies/merges objects immutably — the pattern React state updates depend on.", 'const user = { name: "Asha", city: "Pune", age: 24 };\nconst { name, city } = user;\nconst updated = { ...user, age: 25 };\nconsole.log(name, city, updated.age);'],
                ],
                ex: "Given an array of product objects with name and price, use filter to keep products under ₹500, map to produce strings like 'Pen — ₹40', and reduce to compute the total price of the filtered set.",
                tips: ["Arrow functions are the modern default for callbacks", "map/filter/reduce replace most manual loops", "Spread (...) copies — it never mutates the original"],
            },
            {
                t: "The DOM: Making Pages Interactive", s: "js-dom-basics",
                e: "Select elements, react to clicks, and change the page — the skills behind every interactive website.",
                sec: [
                    ["Selecting and changing elements", "document.querySelector finds the first match for any CSS selector; querySelectorAll finds them all. Change text with textContent, styles via classList (never inline styles), and attributes with setAttribute.", 'const title = document.querySelector("h1");\ntitle.textContent = "Updated by JavaScript";\ntitle.classList.add("highlight");'],
                    ["Events: reacting to the user", "addEventListener attaches a function to run on clicks, typing, submits, and more. The handler receives an event object with details — which key, which element, mouse position. Call event.preventDefault() to stop default behavior like form navigation.", 'const btn = document.querySelector("#save");\nbtn.addEventListener("click", (event) => {\n    console.log("clicked", event.target);\n});\n\ndocument.querySelector("form").addEventListener("submit", (e) => {\n    e.preventDefault();\n    console.log("handled in JS instead");\n});'],
                    ["Creating elements dynamically", "Build UI from data: createElement, set its content, and append it. This is manual React — doing it a few times teaches you exactly what frameworks automate.", 'const list = document.querySelector("#todos");\n["Learn DOM", "Build project"].forEach(text => {\n    const li = document.createElement("li");\n    li.textContent = text;\n    list.append(li);\n});'],
                ],
                ex: "Build a click counter page: a button and a paragraph. Each click increments a counter and updates the paragraph text; at 10 clicks, add a CSS class that turns the text green.",
                tips: ["querySelector accepts any CSS selector", "classList beats inline style manipulation", "preventDefault() stops the browser's default action"],
            },
            {
                t: "Strings, Numbers, and Dates", s: "js-strings-numbers-dates",
                e: "The everyday data types and the built-in methods that save you from reinventing them.",
                sec: [
                    ["String methods you'll use constantly", "Strings have a rich method set: trim(), toLowerCase(), includes(), replaceAll(), split(), and slice(). Template literals with ${} remain the modern way to build text. Strings are immutable — every method returns a new one.", 'const raw = "  Hello, World  ";\nconsole.log(raw.trim().toLowerCase());   // "hello, world"\nconsole.log("a,b,c".split(","));         // ["a","b","c"]'],
                    ["Numbers and their traps", "JavaScript has one number type (floating point), so 0.1 + 0.2 !== 0.3 — round money in the smallest unit (paise/cents). Useful helpers: Number.parseInt/parseFloat, toFixed() for display, and Math for rounding, min/max, and random.", 'console.log((0.1 + 0.2).toFixed(2));   // "0.30"\nconsole.log(Math.round(4.6), Math.max(2, 9, 4));'],
                    ["Dates without tears", "The built-in Date handles timestamps and formatting via toLocaleDateString/toLocaleString. Date math is easiest in milliseconds (getTime). For heavy date work, libraries like day.js are tiny and pleasant — but the basics ship free.", 'const now = new Date();\nconsole.log(now.toLocaleDateString());\nconst inaWeek = new Date(now.getTime() + 7 * 864e5);'],
                ],
                ex: "Write formatPrice(paise) that takes an integer number of paise and returns a string like '₹1,234.50', and daysBetween(a, b) that returns whole days between two date strings.",
                tips: ["String methods return new strings — chain freely", "Store money as integers; round only for display", "Date math is cleanest in milliseconds"],
            },
            {
                t: "Forms, Storage, and Building a Todo App", s: "js-forms-storage",
                e: "Combine everything so far into a real, persistent mini-app running entirely in the browser.",
                sec: [
                    ["Reading form input", "Grab values with element.value, validate before using, and handle the submit event with preventDefault to stay on the page. Forms are how users hand data to your JavaScript.", 'const form = document.querySelector("#todo-form");\nform.addEventListener("submit", (e) => {\n    e.preventDefault();\n    const text = form.task.value.trim();\n    if (text) addTodo(text);\n    form.reset();\n});'],
                    ["Persisting with localStorage", "localStorage keeps string data in the browser across reloads. Store structured data by serializing with JSON.stringify and reading it back with JSON.parse — the simplest persistence there is, perfect for preferences and small app state.", 'function save(todos) {\n    localStorage.setItem("todos", JSON.stringify(todos));\n}\nfunction load() {\n    return JSON.parse(localStorage.getItem("todos") || "[]");\n}'],
                    ["Render from state", "Keep a single source of truth (an array), and re-render the DOM from it after every change. This 'state → UI' discipline is exactly the mental model frameworks like React formalize — learn it here in plain JS.", 'let todos = load();\nfunction render() {\n    list.innerHTML = "";\n    todos.forEach((t, i) => { /* build <li> */ });\n}'],
                ],
                ex: "Build a complete todo app: add tasks via a form, mark them done (toggling a class), delete them, and persist everything to localStorage so the list survives a page reload. Render the whole list from a single state array.",
                tips: ["Always preventDefault on form submits you handle", "localStorage stores strings — use JSON to (de)serialize", "One state array, re-render after every change"],
            },
            {
                t: "Output and Where JavaScript Goes", s: "js-output",
                e: "The ways JavaScript displays data and where the code itself lives in a page.",
                sec: [
                    ["Four ways to output", "JavaScript can show data in several places: writing into an element with innerHTML (the usual choice), logging to the browser console with console.log (for debugging), popping an alert box (intrusive, avoid in real apps), and document.write (only for quick tests — it overwrites the page if run after load).", 'document.getElementById("out").innerHTML = "Hello";\nconsole.log("For developers");\nalert("A blocking popup");   // avoid in production'],
                    ["Where scripts live", "Scripts go in <script> tags, either inline or (better) in external .js files linked with src. Placing scripts just before </body>, or adding defer to a script in the head, ensures the HTML is parsed before the script runs — avoiding 'element is null' errors.", '<script src="app.js" defer></script>\n<!-- or at the end of <body> -->\n<script src="app.js"></script>'],
                    ["console methods beyond log", "The console has more than log: console.error and console.warn for severity, console.table for arrays of objects, console.time/timeEnd for quick timing, and console.assert for sanity checks. These make debugging far more effective than log alone.", 'console.table([{ id: 1, name: "A" }, { id: 2, name: "B" }]);\nconsole.warn("Deprecated");\nconsole.time("loop"); /* ... */ console.timeEnd("loop");'],
                ],
                ex: "Build a page that outputs a value four ways (innerHTML, console.log, and comment on when you'd use alert/document.write). Link an external script with defer and confirm it can access elements without error.",
                tips: ["innerHTML for the page, console.log for debugging", "Load scripts with defer or before </body>", "console.table/time/warn beat plain log for debugging"],
            },
            {
                t: "Operators in Depth", s: "js-operators",
                e: "Every operator you'll use daily — arithmetic, assignment, comparison, logical, and ternary.",
                sec: [
                    ["Arithmetic and assignment", "Arithmetic operators (+ - * / % **) compute values; % is remainder and ** is exponent. Assignment operators combine an operation with assignment (+=, -=, *=, and ++ / -- for increment/decrement). Remember + also concatenates strings.", 'let x = 10;\nx += 5;        // 15\nx %= 4;        // 3 (remainder)\nconsole.log(2 ** 10);   // 1024\nconsole.log("a" + "b"); // "ab" — + concatenates strings'],
                    ["Comparison operators", "Comparisons return booleans: === and !== compare value AND type (always prefer these), while == and != coerce types and cause classic bugs (0 == '' is true). Relational operators (< > <= >=) work on numbers and strings (lexicographically).", 'console.log(5 === "5");   // false — different types\nconsole.log(5 == "5");    // true — coerced (avoid)\nconsole.log("apple" < "banana");   // true'],
                    ["Logical and ternary", "Logical operators combine conditions: && (and), || (or), ! (not). They short-circuit — && stops at the first falsy, || at the first truthy — which enables defaults (x || fallback) and guards (user && user.name). The ternary ?: is a compact if/else expression.", 'const name = input || "Guest";           // default\nconst canEdit = user && user.role === "admin";\nconst label = count === 1 ? "item" : "items";  // ternary'],
                ],
                ex: "Write expressions demonstrating each operator group: compute with %/**, build a string with +, compare with === vs ==, provide a default with ||, guard a property access with &&, and pick a label with a ternary.",
                tips: ["Prefer === / !== over == / != (no coercion)", "&& and || short-circuit — use for guards and defaults", "Ternary ?: is if/else as a value"],
            },
            {
                t: "Conditionals: if, else, and switch", s: "js-conditionals",
                e: "Branch your program's flow based on conditions with the two core control structures.",
                sec: [
                    ["if / else if / else", "The if statement runs a block when its condition is truthy; else if chains alternatives; else is the fallback. Conditions are any expression — JavaScript coerces it to true/false using truthiness rules.", 'if (score >= 90) grade = "A";\nelse if (score >= 75) grade = "B";\nelse if (score >= 60) grade = "C";\nelse grade = "F";'],
                    ["Truthy and falsy", "Every value is either truthy or falsy in a condition. The falsy values are: false, 0, the empty string, null, undefined, and NaN — everything else is truthy. Knowing these prevents subtle bugs (an empty array is truthy!).", 'if (username) { /* runs unless username is "", null, undefined, 0, NaN, false */ }\nif ([].length) { /* [] is truthy but [].length is 0 → falsy */ }'],
                    ["switch", "When comparing one value against many constants, switch is cleaner than a long if/else chain. Each case uses strict comparison; break stops fall-through; default handles unmatched values. Group cases by omitting break intentionally.", 'switch (day) {\n    case "Sat":\n    case "Sun":\n        type = "weekend"; break;\n    default:\n        type = "weekday";\n}'],
                ],
                ex: "Write a function that converts a numeric HTTP status to a category using if/else, then a function that maps a day name to weekend/weekday using switch with grouped cases and a default. Test edge cases.",
                tips: ["if/else if/else for ranges and complex conditions", "Falsy: false, 0, '', null, undefined, NaN — all else truthy", "switch for one value vs many constants; mind break"],
            },
            {
                t: "Loops in Depth", s: "js-loops",
                e: "Every looping construct — for, while, for...of, for...in — and how to control them.",
                sec: [
                    ["for and while", "The classic for loop (init; condition; update) is best when you know the count. while repeats until a condition turns false — ideal when the count is unknown. do...while always runs at least once. break exits a loop; continue skips to the next iteration.", 'for (let i = 0; i < 5; i++) {\n    if (i === 3) continue;   // skip 3\n    console.log(i);          // 0 1 2 4\n}\nlet n = 0;\nwhile (n < 3) { n++; }'],
                    ["for...of for values", "for...of iterates the values of any iterable — arrays, strings, Sets, Maps, NodeLists. It's the cleanest way to loop over a collection when you don't need the index, and it works where for...in shouldn't.", 'for (const item of ["a", "b", "c"]) console.log(item);\nfor (const char of "hi") console.log(char);   // h, i'],
                    ["for...in for keys (and array methods)", "for...in iterates the keys (property names) of an object — use it for plain objects, not arrays (order isn't guaranteed and it includes inherited keys). For arrays, prefer for...of or array methods (forEach, map) which are more expressive and safer.", 'const user = { name: "A", age: 30 };\nfor (const key in user) console.log(key, user[key]);\n\n// arrays: prefer these\n[1, 2, 3].forEach((n, i) => console.log(i, n));'],
                ],
                ex: "Sum an array three ways — a for loop, a for...of loop, and reduce. Loop an object's entries with for...in. Then use break to stop a search loop early and continue to skip odd numbers.",
                tips: ["for/while for counted/conditional loops; break & continue control them", "for...of iterates values of any iterable", "for...in iterates object keys — not for arrays"],
            },
            {
                t: "Type Conversion and Coercion", s: "js-type-conversion",
                e: "How JavaScript changes types — explicitly when you ask, and implicitly when you don't.",
                sec: [
                    ["Explicit conversion", "Convert deliberately with Number(), String(), and Boolean(). parseInt and parseFloat extract numbers from strings (parseInt('12px') is 12). Template literals and String() turn anything into text; Number() turns numeric strings into numbers (and '' into 0, which surprises people).", 'Number("42");       // 42\nNumber("");         // 0  (surprising)\nparseInt("12px");   // 12\nString(true);       // "true"\nBoolean(0);         // false'],
                    ["Implicit coercion", "JavaScript auto-converts types in mixed operations, which is powerful but bug-prone. + with a string concatenates ('5' + 1 = '51'); other math operators convert to number ('5' - 1 = 4). == coerces before comparing. Understanding these rules explains many 'weird' results.", 'console.log("5" + 1);    // "51"  (string concat)\nconsole.log("5" - 1);    // 4     (numeric)\nconsole.log(true + 1);   // 2\nconsole.log([] + {});    // "[object Object]"'],
                    ["NaN, null, and undefined", "NaN ('not a number') results from invalid math and is never equal to anything (use Number.isNaN to test). undefined means a variable has no value yet; null is an intentional 'no value'. typeof null is famously 'object' (a historical bug); typeof NaN is 'number'.", 'console.log(Number("abc"));      // NaN\nconsole.log(Number.isNaN(NaN));  // true\nconsole.log(typeof null);        // "object" (quirk)\nconsole.log(typeof undefined);   // "undefined"'],
                ],
                ex: "Predict then verify the results of several coercion expressions ('5'+1, '5'-1, true+1, []+[]). Write a safe parseNumber(str) that returns a number or a fallback using Number.isNaN. Explain null vs undefined.",
                tips: ["Convert explicitly with Number/String/Boolean/parseInt", "+ concatenates with strings; other math coerces to number", "NaN ≠ everything (use Number.isNaN); typeof null is 'object'"],
            },
            {
                t: "Variables, Scope, and let/const/var", s: "js-var-let-const",
                e: "The three ways to declare variables, how they differ, and the scope rules that govern them.",
                sec: [
                    ["let, const, and var", "const declares a constant binding (can't be reassigned) — the default choice. let declares a reassignable variable. var is the legacy form with confusing scope rules; avoid it in new code. Note const prevents reassignment, not mutation (you can still push to a const array).", 'const PI = 3.14;      // cannot reassign\nlet count = 0;        // can reassign\ncount++;\nconst list = [];      // const, but...\nlist.push(1);         // mutation is allowed'],
                    ["Block scope vs function scope", "let and const are block-scoped — they exist only within the nearest { } (an if, a loop, a function). var is function-scoped, leaking out of blocks, which causes classic loop bugs. Block scope is more predictable, another reason to prefer let/const.", 'if (true) {\n    let a = 1;\n    var b = 2;\n}\n// console.log(a);   // Error — block-scoped\nconsole.log(b);      // 2 — var leaks out'],
                    ["The scope chain", "Inner scopes can read variables from outer scopes (lexical scoping), forming a chain up to the global scope. This is the foundation of closures. Keep variables in the narrowest scope that works — global variables are shared mutable state and a common source of bugs.", 'const outer = "visible inside";\nfunction inner() {\n    console.log(outer);   // reads from the enclosing scope\n}'],
                ],
                ex: "Demonstrate the loop bug that var causes (a for loop with a setTimeout logging i) and fix it with let. Show that const prevents reassignment but allows array mutation. Explain block vs function scope in a comment.",
                tips: ["const by default, let when reassigning, never var", "let/const are block-scoped; var is function-scoped and leaks", "Inner scopes read outer ones — the basis of closures"],
            },
            {
                t: "String Methods in Depth", s: "js-string-methods",
                e: "The full toolkit for searching, extracting, and transforming text.",
                sec: [
                    ["Searching and testing", "Find text with indexOf (position or -1), includes (boolean), startsWith and endsWith. search and match use regular expressions for pattern-based searching. These cover every 'does this contain / where is' question.", 'const s = "Hello, World";\ns.indexOf("World");    // 7\ns.includes("World");   // true\ns.startsWith("Hello"); // true\ns.endsWith("!");       // false'],
                    ["Extracting and slicing", "slice(start, end) extracts a portion (negative indices count from the end); substring is similar without negatives. split turns a string into an array by a separator, and its inverse, Array.join, rebuilds a string.", 'const csv = "a,b,c";\ncsv.split(",");        // ["a","b","c"]\n"Hello".slice(0, 3);   // "Hel"\n"Hello".slice(-2);     // "lo"'],
                    ["Transforming", "Clean and reshape text: trim (and trimStart/trimEnd) remove whitespace, toUpperCase/toLowerCase change case, replace and replaceAll swap text, padStart/padEnd add padding, and repeat duplicates. Strings are immutable — every method returns a new string.", '"  Hi  ".trim();              // "Hi"\n"a-b-c".replaceAll("-", " ");  // "a b c"\n"5".padStart(3, "0");          // "005"\n"ab".repeat(3);                // "ababab"'],
                ],
                ex: "Write functions using string methods: a title-caser, a function that extracts the domain from an email (using indexOf/slice), a CSV parser using split, and a function that masks all but the last 4 digits of a card number using slice and padStart.",
                tips: ["indexOf/includes/startsWith/endsWith to search", "slice/split/join to extract and rebuild", "trim/replace/pad/case transform; strings are immutable"],
            },
            {
                t: "Arrays and Array Methods in Depth", s: "js-arrays-in-depth",
                e: "Master the array methods that replace loops and power modern JavaScript.",
                sec: [
                    ["Adding, removing, and copying", "Mutating methods change the array: push/pop (end), shift/unshift (start), splice (insert/remove anywhere). Non-mutating methods return new arrays: slice (copy a portion), concat and the spread operator (combine). Prefer non-mutating in modern code.", 'const a = [1, 2, 3];\na.push(4);              // [1,2,3,4] (mutates)\nconst b = [...a, 5];    // copy + add (no mutation)\na.splice(1, 1);         // remove 1 item at index 1'],
                    ["Transforming: map, filter, reduce", "The big three: map transforms every element into a new array, filter keeps elements passing a test, reduce boils an array down to a single value (sum, object, grouping). Chaining them expresses complex data pipelines declaratively.", 'const nums = [1, 2, 3, 4, 5];\nnums.map(n => n * 2);              // [2,4,6,8,10]\nnums.filter(n => n % 2 === 0);    // [2,4]\nnums.reduce((sum, n) => sum + n, 0);  // 15'],
                    ["Searching, sorting, and iterating", "find/findIndex locate an element by test; some/every test the whole array; includes/indexOf find a value. sort orders in place (pass a comparator for numbers!), reverse flips it, and forEach iterates for side effects. flat/flatMap handle nested arrays.", 'const users = [{ age: 30 }, { age: 20 }];\nusers.find(u => u.age > 25);          // { age: 30 }\n[3, 1, 2].sort((a, b) => a - b);      // [1,2,3] (numeric)\n[1, [2, [3]]].flat(Infinity);         // [1,2,3]'],
                ],
                ex: "Given an array of product objects, use a method chain to: filter in-stock items, map to their prices with tax, and reduce to a total. Separately, sort products by price (numeric comparator) and find the first over ₹1000.",
                tips: ["push/splice mutate; slice/spread/concat return new arrays", "map/filter/reduce are the core transformation trio", "sort needs a comparator for numbers; find/some/every to search"],
            },
        ],
        Intermediate: [
            {
                t: "Asynchronous JavaScript: Promises and async/await", s: "js-async-await",
                e: "JavaScript never waits — understand the event loop, promises, and the async/await syntax that tamed them.",
                sec: [
                    ["Why async exists", "JavaScript runs on one thread. If fetching data blocked it, the whole page would freeze. Instead, slow operations start in the background and your code continues; callbacks/promises deliver the result later via the event loop's queue."],
                    ["Promises and fetch", "A promise represents a value that will arrive: pending → fulfilled or rejected. fetch() returns one. Chain .then() for results and .catch() for failures — and remember fetch only rejects on network failure; check response.ok for HTTP errors.", 'fetch("https://api.github.com/users/torvalds")\n    .then(res => {\n        if (!res.ok) throw new Error(`HTTP ${res.status}`);\n        return res.json();\n    })\n    .then(user => console.log(user.name))\n    .catch(err => console.error("Failed:", err.message));'],
                    ["async/await: promises that read like prose", "async functions let you await promises with try/catch error handling — same behavior, dramatically clearer code. Run independent operations in parallel with Promise.all instead of awaiting one by one.", 'async function loadDashboard() {\n    try {\n        const [user, repos] = await Promise.all([\n            fetch("/api/user").then(r => r.json()),\n            fetch("/api/repos").then(r => r.json()),\n        ]);\n        console.log(user.name, repos.length);\n    } catch (err) {\n        console.error("Dashboard failed:", err);\n    }\n}'],
                ],
                ex: "Use the free JSONPlaceholder API: write an async function that fetches /users and /posts in parallel with Promise.all, then prints each user's name with their post count. Handle a failing URL gracefully.",
                tips: ["The event loop lets one thread feel concurrent", "Check response.ok — fetch doesn't reject on 404", "Promise.all for independent work; sequential await only when dependent"],
            },
            {
                t: "Closures, Scope, and the Weird Parts", s: "js-closures-scope",
                e: "The concepts interviewers love and bugs hide behind: scope chains, closures, hoisting, and this.",
                sec: [
                    ["Scope and closures", "A closure is a function that remembers the variables where it was created, even after that scope has finished. It's how JavaScript does private state — the counter below can't be modified except through its methods.", 'function makeCounter() {\n    let count = 0;\n    return {\n        increment: () => ++count,\n        current: () => count,\n    };\n}\nconst counter = makeCounter();\ncounter.increment();\ncounter.increment();\nconsole.log(counter.current()); // 2 — count is private'],
                    ["Hoisting and the TDZ", "Declarations are processed before execution: function declarations hoist fully (callable before their line), while let/const hoist but stay in a 'temporal dead zone' until declared — accessing them early throws. This is why const/let are safer than var, which silently yields undefined."],
                    ["Understanding this", "this depends on HOW a function is called, not where it's written: method call → the object; plain call → undefined (strict mode); arrow functions don't have their own this — they inherit from the surrounding scope, which is exactly why arrows are perfect for callbacks inside methods.", 'const timer = {\n    seconds: 0,\n    start() {\n        setInterval(() => {\n            this.seconds++;   // arrow inherits `this` = timer\n        }, 1000);\n    },\n};'],
                ],
                ex: "Write a createBank() function using closures: it returns deposit(amount), withdraw(amount), and balance() functions where the balance variable is completely inaccessible from outside. Withdrawals beyond the balance should throw.",
                tips: ["Closures = functions with a memory of their birthplace", "let/const throw before declaration; var silently doesn't", "Arrow functions inherit this — use them for callbacks"],
            },
            {
                t: "Modern Tooling: Modules, npm, and the Browser Toolchain", s: "js-modern-tooling",
                e: "How real projects are structured: ES modules, npm scripts, and the bundler pipeline behind every framework.",
                sec: [
                    ["ES modules", "import/export split code across files with explicit dependencies. Named exports for utilities, default export for a file's main thing. In browsers, use <script type=\"module\">; in Node, set \"type\": \"module\" in package.json.", '// utils.js\nexport const TAX = 0.18;\nexport function withTax(price) { return price * (1 + TAX); }\n\n// main.js\nimport { withTax } from "./utils.js";\nconsole.log(withTax(100)); // 118'],
                    ["npm: the package ecosystem", "package.json records your dependencies and scripts. npm install adds libraries into node_modules; npm run executes scripts. Know the difference: dependencies ship with your app, devDependencies (test runners, bundlers) don't.", 'npm init -y\nnpm install dayjs\nnpm install --save-dev vitest\n\n// package.json scripts\n"scripts": { "test": "vitest", "dev": "vite" }'],
                    ["What bundlers actually do", "Browsers want few, small files; developers want many, readable ones. Bundlers (Vite, esbuild, webpack) resolve your imports into optimized bundles, transpile modern syntax for older browsers, and hot-reload during development. Vite is today's easiest start: `npm create vite@latest`."],
                ],
                ex: "Create a Vite project, split the earlier product-filtering exercise into a data.js module and a render.js module, import both into main.js, and display the results on the page instead of the console.",
                tips: ["Explicit import/export beats global scripts", "dependencies vs devDependencies matters at deploy time", "Vite is the fastest way to a modern JS project"],
            },
            {
                t: "Working With APIs and Real Data", s: "js-apis-real-data",
                e: "Fetch, send, and handle data from servers — the core skill behind every dynamic web app.",
                sec: [
                    ["GET and POST with fetch", "fetch defaults to GET; for POST, pass method, headers, and a JSON body. Always await response.json() and check response.ok. This request/response cycle is 80% of front-end/back-end interaction.", 'async function createUser(data) {\n    const res = await fetch("/api/users", {\n        method: "POST",\n        headers: { "Content-Type": "application/json" },\n        body: JSON.stringify(data),\n    });\n    if (!res.ok) throw new Error(`HTTP ${res.status}`);\n    return res.json();\n}'],
                    ["Loading, error, and empty states", "Real UIs have four states, not one: loading, error, empty, and success. Handling all four is what separates a robust app from a demo that breaks the moment the network hiccups. Show a spinner, catch failures, and design for zero results.", 'setLoading(true);\ntry {\n    const data = await getData();\n    render(data.length ? data : emptyState());\n} catch {\n    render(errorState());\n} finally {\n    setLoading(false);\n}'],
                    ["CORS and auth basics", "Browsers block cross-origin requests unless the server opts in via CORS headers — a concept that confuses every beginner exactly once. For protected APIs, send credentials via an Authorization header (bearer token) and never hardcode secrets in front-end code, which anyone can read."],
                ],
                ex: "Build a GitHub user search: an input, a fetch to the GitHub API on submit, and rendering of the avatar, name, and repo count — with explicit loading, error (invalid user), and empty states.",
                tips: ["Check response.ok — fetch doesn't reject on 4xx/5xx", "Design for loading, error, empty, and success", "Front-end code is public — never embed secrets"],
            },
            {
                t: "Debugging and DevTools Mastery", s: "js-debugging-devtools",
                e: "The skill that pays off every single day — find and fix bugs fast instead of guessing.",
                sec: [
                    ["Breakpoints beat console.log", "The Sources panel lets you pause execution, inspect every variable, and step through line by line. Conditional breakpoints stop only when a condition holds — vastly faster than scattering logs and reloading.", '// Or drop a breakpoint in code:\nfunction risky(x) {\n    debugger;   // execution pauses here in DevTools\n    return x * 2;\n}'],
                    ["Reading errors and the call stack", "An error message plus its stack trace usually names the exact file, line, and chain of calls. Read from the top (where it threw) down (how you got there). 'Cannot read properties of undefined' — the most common JS error — means you accessed a property on something that wasn't there; optional chaining (?.) prevents it."],
                    ["Network and console tools", "The Network panel shows every request, its status, timing, and payload — indispensable for API debugging. The console does more than log: console.table for arrays of objects, console.time for quick timing, and console.assert for sanity checks."],
                ],
                ex: "Take a small broken script (or intentionally break one), then fix it using DevTools only: set a breakpoint, inspect the failing variable, read the stack trace, and confirm the fix in the Network panel — without adding a single console.log.",
                tips: ["Breakpoints + step-through beat scattering logs", "Read stack traces top-down", "Optional chaining (?.) prevents the #1 JS error"],
            },
            {
                t: "Numbers, Math, and Random", s: "js-numbers-math",
                e: "Work precisely with numbers, format them, and use the Math object.",
                sec: [
                    ["Number methods and precision", "JavaScript has one number type (64-bit float), so decimals aren't exact (0.1 + 0.2 !== 0.3). Format for display with toFixed (decimals) and toLocaleString (grouping/currency). Parse and validate with Number.parseFloat, Number.isInteger, and Number.isFinite.", 'console.log((0.1 + 0.2).toFixed(2));       // "0.30"\n(1234567.89).toLocaleString("en-IN");      // "12,34,567.89"\nNumber.isInteger(5);                       // true'],
                    ["The Math object", "Math provides rounding (round, floor, ceil, trunc), powers and roots (pow, sqrt, cbrt), min/max, abs, and constants (Math.PI). These cover most numeric computation without any library.", 'Math.round(4.6);       // 5\nMath.floor(4.9);       // 4\nMath.max(2, 9, 4);     // 9\nMath.sqrt(144);        // 12'],
                    ["Random numbers and BigInt", "Math.random returns a float in [0, 1); scale and floor it for ranges. For integers larger than Number can safely hold (beyond 2^53), use BigInt (the n suffix) — essential for large IDs and precise big-integer math.", 'const roll = Math.floor(Math.random() * 6) + 1;   // 1–6\nconst huge = 9007199254740993n;   // BigInt, exact\nconsole.log(huge + 1n);'],
                ],
                ex: "Write a formatMoney function using toLocaleString, a randomInt(min, max) helper, and a function that rounds to a given number of decimals. Demonstrate a floating-point precision issue and how toFixed hides it for display.",
                tips: ["One float type — decimals aren't exact; format with toFixed/toLocaleString", "Math handles rounding, powers, min/max, constants", "Math.random for randomness; BigInt for huge exact integers"],
            },
            {
                t: "Dates and Times", s: "js-dates",
                e: "Create, read, format, and calculate with dates using the built-in Date object.",
                sec: [
                    ["Creating and reading dates", "new Date() is now; pass a timestamp, an ISO string, or year/month/day parts to make specific dates (months are 0-indexed — a classic trap). Getter methods read components: getFullYear, getMonth, getDate, getHours, getDay (weekday).", 'const now = new Date();\nconst d = new Date("2026-01-15");\nconst parts = new Date(2026, 0, 15);   // Jan (month 0!)\nconsole.log(now.getFullYear(), now.getMonth());'],
                    ["Formatting", "For display, toLocaleDateString and toLocaleString produce human, locale-aware output; toISOString gives the standard machine format (great for storage and APIs). Avoid building date strings by hand — use these or a library.", 'now.toLocaleDateString("en-IN");   // "15/1/2026"\nnow.toLocaleString();               // date + time\nnow.toISOString();                  // "2026-01-15T..."'],
                    ["Date math", "Dates are milliseconds since 1970 under the hood, so differences and offsets are easiest in milliseconds: getTime() gives the number, subtract two for a duration, add days as ms. For heavy date work, a small library (day.js) is far less error-prone than manual math.", 'const start = new Date("2026-01-01").getTime();\nconst end = new Date("2026-01-31").getTime();\nconst days = (end - start) / (1000 * 60 * 60 * 24);   // 30\nconst tomorrow = new Date(Date.now() + 864e5);'],
                ],
                ex: "Write functions: daysBetween(a, b) using getTime, addDays(date, n), and a formatter that outputs 'Jan 15, 2026'. Demonstrate the 0-indexed month trap and how to avoid it.",
                tips: ["Months are 0-indexed in Date — a common bug", "Format with toLocaleDateString/toISOString, not by hand", "Do date math in milliseconds via getTime()"],
            },
            {
                t: "Objects in Depth", s: "js-objects-in-depth",
                e: "Everything about objects — properties, methods, this, getters/setters, and useful static helpers.",
                sec: [
                    ["Properties and methods", "Objects hold key-value pairs; values can be functions (methods). Access with dot or bracket notation (brackets for dynamic keys). Shorthand and computed keys keep object creation concise.", 'const key = "score";\nconst player = {\n    name: "Asha",\n    [key]: 100,               // computed key\n    greet() { return `Hi, ${this.name}`; },  // method\n};\nplayer["name"];   // bracket access'],
                    ["this in objects, getters and setters", "Inside a method, this refers to the object the method was called on. Getters and setters (get/set) let a property run logic on read/write — useful for computed or validated properties that still look like plain fields.", 'const account = {\n    balance: 0,\n    get formatted() { return `₹${this.balance}`; },\n    set deposit(amount) { this.balance += amount; },\n};\naccount.deposit = 500;\nconsole.log(account.formatted);   // "₹500"'],
                    ["Object static helpers", "Object.keys/values/entries turn an object into arrays for iteration; Object.assign and spread copy/merge; Object.freeze makes it immutable. These are the everyday tools for working with object data.", 'const user = { name: "A", age: 30 };\nObject.keys(user);              // ["name","age"]\nObject.entries(user).forEach(([k, v]) => console.log(k, v));\nconst copy = { ...user, age: 31 };   // merge/override'],
                ],
                ex: "Model a rectangle object with width/height, a get area computed property, and a method scale(factor). Then use Object.entries to print all properties, and create an updated copy with the spread operator without mutating the original.",
                tips: ["Dot vs bracket access; computed keys and method shorthand", "this = the calling object; get/set add logic to properties", "Object.keys/values/entries + spread for iterating and copying"],
            },
            {
                t: "Sets and Maps", s: "js-sets-maps",
                e: "Two modern collections that solve problems plain objects and arrays handle awkwardly.",
                sec: [
                    ["Set: unique values", "A Set stores unique values in insertion order — deduplicating is a one-liner. It offers add, has (fast membership test, unlike array includes), delete, and size, and is iterable with for...of.", 'const tags = new Set(["a", "b", "a", "c"]);\nconsole.log(tags.size);          // 3 (deduped)\nconsole.log(tags.has("b"));      // true\nconst unique = [...new Set([1, 1, 2, 3])];   // [1,2,3]'],
                    ["Map: keyed collections", "A Map is a key-value collection where keys can be any type (not just strings, unlike objects), remembers insertion order, and has a reliable size. Use get/set/has/delete and iterate entries directly — ideal when keys are dynamic or non-string.", 'const scores = new Map();\nscores.set("asha", 91);\nscores.set("ravi", 84);\nscores.get("asha");   // 91\nfor (const [name, score] of scores) console.log(name, score);'],
                    ["When to use which", "Reach for a Set to enforce uniqueness or do fast membership checks; reach for a Map when you need non-string keys, guaranteed order, easy size, or frequent additions/deletions. Plain objects still suit fixed, string-keyed records — pick the tool that fits."],
                ],
                ex: "Use a Set to dedupe an array and to track 'seen' items in a loop. Use a Map to count word frequencies in a sentence (word → count), then print the top word. Explain when you'd choose each over an array/object.",
                tips: ["Set stores unique values; fast has() and easy dedupe", "Map allows any key type, keeps order, has size", "Set for uniqueness/membership; Map for dynamic keyed data"],
            },
            {
                t: "JSON: Data Interchange", s: "js-json",
                e: "The format that carries data between browsers, servers, and files — and how to work with it.",
                sec: [
                    ["What JSON is", "JSON (JavaScript Object Notation) is a text format for structured data — objects, arrays, strings, numbers, booleans, null. It's the universal language of web APIs and config files. It looks like JavaScript object literals but is stricter: double-quoted keys, no functions, no comments.", '{\n  "name": "Asha",\n  "roles": ["admin", "editor"],\n  "active": true,\n  "age": 30\n}'],
                    ["parse and stringify", "JSON.parse turns a JSON string into a JavaScript value; JSON.stringify turns a value into a JSON string. stringify takes options: a replacer to filter fields and an indent for pretty-printing. This pair is how you send, store, and read structured data.", 'const obj = JSON.parse(\'{"a": 1}\');       // → { a: 1 }\nconst str = JSON.stringify(obj);          // → \'{"a":1}\'\nconst pretty = JSON.stringify(obj, null, 2);   // indented'],
                    ["Working with APIs and pitfalls", "fetch responses use res.json() (parse) and requests send JSON.stringify(body). Watch the gotchas: parse throws on invalid JSON (wrap in try/catch), dates become strings (JSON has no date type), and undefined/functions are dropped by stringify.", 'const res = await fetch("/api/user");\nconst user = await res.json();          // parses for you\n\nawait fetch("/api/user", {\n    method: "POST",\n    body: JSON.stringify({ name: "New" }),\n});'],
                ],
                ex: "Round-trip data: create an object, stringify it (pretty and compact), parse it back, and confirm equality of a field. Wrap a parse of deliberately-broken JSON in try/catch. Note what happens to a Date and an undefined field through stringify.",
                tips: ["JSON is the universal structured-data text format", "JSON.parse (string→value), JSON.stringify (value→string)", "parse throws on bad input; dates/undefined don't survive stringify"],
            },
            {
                t: "Destructuring, Spread, and Rest", s: "js-destructuring-spread",
                e: "Modern syntax that makes working with arrays and objects concise and readable.",
                sec: [
                    ["Destructuring", "Destructuring unpacks values from arrays (by position) and objects (by name) into variables in one line. Add defaults for missing values and rename object keys. It's everywhere in modern code — function params, imports, React state.", 'const [first, second] = [10, 20];\nconst { name, role = "guest" } = user;\nconst { name: userName } = user;   // rename\nfunction greet({ name, age }) { /* destructured param */ }'],
                    ["Spread", "The spread operator (...) expands an iterable into individual elements — copying and merging arrays and objects immutably, and passing array elements as function arguments. It's the idiomatic way to update state without mutation.", 'const combined = [...arr1, ...arr2];\nconst updated = { ...user, age: 31 };   // copy + override\nMath.max(...[3, 7, 2]);                 // spread as arguments'],
                    ["Rest", "The rest pattern (...) collects the remaining items into an array or object — the inverse of spread. Use it to gather leftover destructured values or to accept a variable number of function arguments.", 'const [head, ...tail] = [1, 2, 3, 4];   // head=1, tail=[2,3,4]\nconst { id, ...rest } = user;           // rest = everything but id\nfunction sum(...nums) { return nums.reduce((a, b) => a + b, 0); }'],
                ],
                ex: "Use destructuring to swap two variables, pull fields from a nested object with a rename and a default, and write a function taking a destructured options object. Use spread to merge two objects and rest to collect extra function arguments.",
                tips: ["Destructure arrays by position, objects by name (with defaults)", "Spread copies/merges immutably and expands arguments", "Rest gathers leftovers — the inverse of spread"],
            },
            {
                t: "Regular Expressions", s: "js-regex",
                e: "Match, validate, and extract text patterns — a powerful tool once it clicks.",
                sec: [
                    ["Patterns and flags", "A regex describes a text pattern between slashes, with flags after: g (global, all matches), i (case-insensitive), m (multiline). Character classes (\\d digit, \\w word char, \\s space), quantifiers (+ * ? {n}), and anchors (^ $) build patterns.", 'const digits = /\\d+/g;          // one or more digits, all matches\nconst word = /\\w+/;\nconst emailish = /^[\\w.]+@[\\w.]+\\.\\w+$/i;'],
                    ["Testing and matching", "test returns a boolean (does it match?) — perfect for validation. match and matchAll return the matched text and capture groups. Parentheses create capture groups you can extract.", 'const re = /(\\d{4})-(\\d{2})-(\\d{2})/;\nre.test("2026-01-15");                  // true\nconst m = "2026-01-15".match(re);\nconsole.log(m[1], m[2], m[3]);          // "2026" "01" "15"'],
                    ["Replacing with patterns", "replace and replaceAll accept a regex and can reference capture groups in the replacement ($1, $2) or use a function for dynamic replacements. This makes complex text transformations concise.", '"2026-01-15".replace(/(\\d+)-(\\d+)-(\\d+)/, "$3/$2/$1");  // "15/01/2026"\n"hello world".replace(/\\w+/g, w => w.toUpperCase());     // "HELLO WORLD"'],
                ],
                ex: "Write regexes to validate an email and an Indian phone number, extract all hashtags from a string with matchAll, and reformat a date from YYYY-MM-DD to DD/MM/YYYY using capture groups in replace.",
                tips: ["Flags: g (all), i (case), m (multiline); classes \\d \\w \\s", "test for validation; match/matchAll to extract", "replace with $1/$2 or a function transforms text"],
            },
            {
                t: "Error Handling", s: "js-errors",
                e: "Write robust code that anticipates failure with try/catch, throw, and custom errors.",
                sec: [
                    ["try / catch / finally", "Wrap code that might fail in try; handle the failure in catch (which receives the error object); finally runs regardless — for cleanup like closing resources. This keeps one bad operation from crashing the whole program.", 'try {\n    const data = JSON.parse(input);\n    process(data);\n} catch (err) {\n    console.error("Failed:", err.message);\n} finally {\n    cleanup();   // always runs\n}'],
                    ["throw and Error types", "throw raises an error — throw actual Error objects (not strings) so they carry a message and stack trace. Built-in types (TypeError, RangeError) categorize failures. Throw early when inputs are invalid, so bugs surface at the source.", 'function withdraw(amount) {\n    if (amount <= 0) throw new Error("Amount must be positive");\n    if (amount > balance) throw new RangeError("Insufficient funds");\n    balance -= amount;\n}'],
                    ["Custom errors and async", "Extend Error for domain-specific types you can catch selectively. In async code, errors in awaited operations are caught by a surrounding try/catch — the same mental model as synchronous code, which is a key benefit of async/await over callbacks.", 'class ValidationError extends Error {}\ntry {\n    await saveUser(data);\n} catch (err) {\n    if (err instanceof ValidationError) showFieldErrors(err);\n    else showGenericError();\n}'],
                ],
                ex: "Write a safeParse(json) that returns a result object instead of throwing. Write a validateAge that throws a RangeError for out-of-range input. Create a custom NotFoundError class and catch it selectively in an async function.",
                tips: ["try/catch/finally contains failures; finally always runs", "throw Error objects, not strings; throw early on bad input", "Custom Error subclasses enable selective catching; async uses try/catch"],
            },
        ],
        Advanced: [
            {
                t: "JavaScript Performance: Rendering, Memory, and the Event Loop in Depth", s: "js-performance",
                e: "Why pages jank, where memory leaks hide, and the profiling workflow that finds both.",
                sec: [
                    ["The 16ms budget", "Smooth UIs render at 60fps, giving you ~16ms per frame for JS, style, layout, and paint. Long tasks block input and animation. Batch DOM reads and writes separately — interleaving them forces synchronous layout ('layout thrashing'), the classic silent killer.", '// BAD: read-write-read-write forces layout each loop\nitems.forEach(el => {\n    const h = el.offsetHeight;      // read\n    el.style.height = h * 2 + "px"; // write\n});\n\n// GOOD: batch reads, then writes\nconst heights = items.map(el => el.offsetHeight);\nitems.forEach((el, i) => el.style.height = heights[i] * 2 + "px");'],
                    ["Microtasks vs macrotasks", "Promise callbacks (microtasks) run before setTimeout callbacks (macrotasks) — the queue order explains countless 'why does this log first?' mysteries and matters when you're yielding to keep the UI responsive.", 'console.log("1");\nsetTimeout(() => console.log("4"));\nPromise.resolve().then(() => console.log("3"));\nconsole.log("2");\n// Output: 1 2 3 4'],
                    ["Memory leaks in long-lived apps", "SPAs leak through forgotten event listeners, timers, and detached DOM kept alive by closures. Remove listeners on teardown (or use AbortController), clear intervals, and use the DevTools Memory panel: two heap snapshots around a suspect action reveal what grew."],
                ],
                ex: "Build a page rendering 5,000 list items. Profile it with the Performance tab, then optimize: build rows in a DocumentFragment, batch reads/writes, and compare the before/after flame charts.",
                tips: ["Batch DOM reads and writes separately", "Microtasks (promises) run before macrotasks (timers)", "Every addEventListener needs a removal story"],
            },
            {
                t: "TypeScript for JavaScript Developers", s: "typescript-for-js-devs",
                e: "The 20% of TypeScript that delivers 80% of the value — catching bugs at compile time instead of production.",
                sec: [
                    ["Types at the boundaries", "Annotate function parameters, returns, and data shapes; let inference handle the rest. Interfaces describe objects; unions describe alternatives. The compiler now catches typos, missing fields, and wrong arguments as you type.", 'interface Order {\n    id: number;\n    amount: number;\n    status: "pending" | "paid" | "cancelled";\n}\n\nfunction totalPaid(orders: Order[]): number {\n    return orders\n        .filter(o => o.status === "paid")\n        .reduce((sum, o) => sum + o.amount, 0);\n}'],
                    ["Narrowing and null safety", "With strictNullChecks on, TypeScript forces you to handle null/undefined — the single largest bug class in JS. Narrow with typeof checks, the in operator, and discriminated unions; after a check, the compiler knows the type.", 'type ApiResult =\n    | { ok: true; data: string[] }\n    | { ok: false; error: string };\n\nfunction handle(res: ApiResult) {\n    if (res.ok) {\n        console.log(res.data.length);  // data exists here\n    } else {\n        console.error(res.error);      // error exists here\n    }\n}'],
                    ["Generics without fear", "Generics are just type parameters: 'this function works for any T and preserves it'. You've used them forever (Array<string>); writing your own turns copy-pasted utilities into one safe function.", 'function firstOrDefault<T>(items: T[], fallback: T): T {\n    return items.length ? items[0] : fallback;\n}\n\nconst n = firstOrDefault([1, 2, 3], 0);        // number\nconst s = firstOrDefault<string>([], "none");  // string'],
                ],
                ex: "Convert your bank-closure exercise to TypeScript: define an Account interface, type every function, model withdraw failures with a discriminated union result type instead of throwing, and compile with strict mode on.",
                tips: ["Type boundaries; infer locals", "strictNullChecks eliminates the biggest JS bug class", "Discriminated unions make invalid states unrepresentable"],
            },
            {
                t: "Design Patterns and Architecture in Modern JS", s: "js-design-patterns",
                e: "Patterns that survive framework churn: modules, observers, state machines, and dependency injection.",
                sec: [
                    ["Observer / pub-sub", "Decouple producers from consumers: emitters publish events, subscribers react, neither knows the other. It's the pattern beneath DOM events, Node streams, and every state library — and trivial to build.", 'function createEmitter() {\n    const handlers = new Map();\n    return {\n        on(event, fn) {\n            (handlers.get(event) ?? handlers.set(event, []).get(event)).push(fn);\n        },\n        emit(event, data) {\n            (handlers.get(event) || []).forEach(fn => fn(data));\n        },\n    };\n}'],
                    ["State machines for UI logic", "Booleans multiply into impossible states (isLoading && isError && hasData?). A state machine names each state and legal transitions — bugs become unrepresentable and the UI logic becomes a diagram you can read.", 'const machine = {\n    idle:    { FETCH: "loading" },\n    loading: { SUCCESS: "done", FAIL: "error" },\n    error:   { RETRY: "loading" },\n    done:    {},\n};\n\nfunction transition(state, event) {\n    return machine[state][event] ?? state;\n}'],
                    ["Dependency injection for testability", "Functions that create their own dependencies (fetch, database, clock) are untestable. Pass dependencies in — production wires real ones, tests wire fakes. This one habit makes 90% of code unit-testable without mocking frameworks.", 'function createUserService({ http, now = () => new Date() }) {\n    return {\n        async register(email) {\n            return http.post("/users", { email, at: now().toISOString() });\n        },\n    };\n}\n// test: createUserService({ http: fakeHttp, now: () => fixedDate })'],
                ],
                ex: "Build a tiny download-manager module combining all three patterns: a state machine (idle/downloading/paused/done), an emitter publishing progress events, and injected transport so tests can simulate a download without a network.",
                tips: ["Pub-sub decouples who-does from who-reacts", "Name your states; stop multiplying booleans", "Inject dependencies — testability is a design property"],
            },
            {
                t: "Testing JavaScript with Vitest", s: "js-testing-vitest",
                e: "Ship with confidence: unit tests, mocks, and the testing mindset that lets you refactor fearlessly.",
                sec: [
                    ["Your first tests", "Vitest (Jest-compatible, Vite-native) discovers *.test.js files. Structure with describe/it and assert with expect. A test names a behavior, runs it, and checks the result — the safety net that turns 'I think this works' into 'I know'.", 'import { describe, it, expect } from "vitest";\nimport { withTax } from "./utils.js";\n\ndescribe("withTax", () => {\n    it("adds 18% GST", () => {\n        expect(withTax(100)).toBe(118);\n    });\n});'],
                    ["Mocking and spying", "Isolate the unit under test by faking its dependencies: vi.fn() creates spies, vi.mock() replaces modules, and you can fake timers and fetch. Test your logic, not the network or the clock.", 'import { vi, expect, it } from "vitest";\nit("calls the API once", async () => {\n    const http = { post: vi.fn().mockResolvedValue({ id: 1 }) };\n    await register(http, "a@b.com");\n    expect(http.post).toHaveBeenCalledOnce();\n});'],
                    ["What to test (and what not to)", "Test behavior and edge cases (empty inputs, boundaries, errors), not implementation details that change on every refactor. Aim for confidence, not a coverage number. The best tests double as documentation of how code is meant to be used."],
                ],
                ex: "Take your bank-closure module, install Vitest, and write a suite: deposits increase balance, over-withdrawal throws, and balance stays private. Include one test using a mock for an injected logger dependency.",
                tips: ["Name behaviors; assert with expect", "Mock dependencies to isolate the unit", "Test behavior and edge cases, not internals"],
            },
            {
                t: "Frameworks and What's Next", s: "js-frameworks-next-steps",
                e: "Understand what React and its peers actually solve, and chart a deliberate path to specialization.",
                sec: [
                    ["Why frameworks exist", "Everything you built by hand — syncing state to the DOM, re-rendering on change, componentizing UI — is what React, Vue, and Svelte automate. Knowing the vanilla version makes the framework's magic legible: components are functions, state triggers re-render, props flow down.", 'function Counter() {\n    const [count, setCount] = useState(0);\n    return <button onClick={() => setCount(count + 1)}>{count}</button>;\n}'],
                    ["The modern ecosystem", "React dominates hiring; Next.js adds server rendering and routing; Vue and Svelte offer gentler curves. Around them: a component library, a data-fetching tool (TanStack Query), and TypeScript. Pick one framework and go deep — the concepts transfer, the syntax is trivia."],
                    ["A deliberate learning path", "From here: (1) solidify JS + TypeScript, (2) learn React via the official docs by building projects, (3) add Next.js for full-stack, (4) learn one styling approach and testing. Build and ship real projects — a deployed portfolio teaches more than any tutorial, and it's what gets you hired."],
                ],
                ex: "Rebuild your vanilla todo app in React (use a Vite React template). Notice what the framework removes: no manual querySelector, no manual re-render — just state and JSX. Write a short note comparing the two versions.",
                tips: ["Frameworks automate the state→DOM work you did by hand", "Pick one framework, go deep — concepts transfer", "Shipped projects teach and get you hired"],
            },
            {
                t: "Classes and Inheritance", s: "js-classes",
                e: "Model objects with the class syntax — constructors, methods, statics, and extends.",
                sec: [
                    ["Class basics", "A class is a blueprint for objects. The constructor initializes each instance; methods are shared behavior. Create instances with new. Under the hood classes are functions over prototypes (next lesson), but the syntax is clean and familiar.", 'class Animal {\n    constructor(name) { this.name = name; }\n    speak() { return `${this.name} makes a sound`; }\n}\nconst dog = new Animal("Rex");\ndog.speak();'],
                    ["Inheritance with extends and super", "A subclass extends a parent, inheriting its members and adding or overriding its own. super() calls the parent constructor; super.method() calls the parent's version. Keep hierarchies shallow — composition often beats deep inheritance.", 'class Dog extends Animal {\n    constructor(name, breed) {\n        super(name);        // call parent constructor\n        this.breed = breed;\n    }\n    speak() { return `${this.name} barks`; }   // override\n}'],
                    ["Static members and private fields", "static methods/properties belong to the class itself, not instances (factory methods, constants). Fields prefixed with # are truly private — inaccessible outside the class — for real encapsulation. Getters/setters work in classes too.", 'class Counter {\n    #count = 0;                     // private\n    static create() { return new Counter(); }   // static factory\n    increment() { return ++this.#count; }\n    get value() { return this.#count; }\n}'],
                ],
                ex: "Build a class hierarchy: a Shape base with an area() method, and Circle and Rectangle subclasses that override it using super for shared setup. Add a private field, a static factory method, and a getter.",
                tips: ["constructor initializes; methods are shared; new makes instances", "extends + super for inheritance; keep hierarchies shallow", "static = class-level; #field = truly private"],
            },
            {
                t: "Prototypes and Prototypal Inheritance", s: "js-prototypes",
                e: "Understand the object-linking mechanism beneath classes — the real heart of JavaScript's object model.",
                sec: [
                    ["The prototype chain", "Every object has a hidden link to a prototype object. When you access a property, JavaScript looks on the object, then its prototype, then that prototype's prototype — up the chain until found or null. This is how inheritance actually works; classes are syntax over it.", 'const arr = [1, 2, 3];\n// arr.map exists on Array.prototype, not on arr itself\nconsole.log(Object.getPrototypeOf(arr) === Array.prototype);   // true'],
                    ["Shared methods live on the prototype", "Methods defined in a class live on its prototype, so all instances share one copy (memory-efficient) rather than each carrying its own. Adding to a prototype affects all existing and future instances — powerful, and the basis of how built-ins like Array work.", 'class Point { move() {} }\nconst p = new Point();\nconsole.log(p.move === Point.prototype.move);   // true — shared'],
                    ["Object.create and delegation", "Object.create makes a new object with a chosen prototype, expressing inheritance without classes. This 'delegation' model — objects linked to objects — is JavaScript's native paradigm. Understanding it demystifies this, method lookup, and framework internals.", 'const base = { greet() { return `Hi, ${this.name}`; } };\nconst user = Object.create(base);\nuser.name = "Asha";\nuser.greet();   // "Hi, Asha" — found on the prototype'],
                ],
                ex: "Inspect the prototype chain of an array and a plain object with Object.getPrototypeOf. Create an object with Object.create linked to a prototype holding a method, and confirm the method is shared, not copied.",
                tips: ["Property lookup walks the prototype chain until found", "Class methods live on the prototype — shared across instances", "Object.create links objects directly (delegation) — JS's native model"],
            },
            {
                t: "this, call, apply, and bind", s: "js-this-binding",
                e: "Master the most confusing keyword in JavaScript — what this points to and how to control it.",
                sec: [
                    ["this depends on how a function is called", "this isn't fixed by where a function is written but by how it's called: a method call (obj.fn()) → obj; a plain call (fn()) → undefined in strict mode; new Fn() → the new instance; an event handler → the element. This call-site rule explains most this confusion.", 'const obj = {\n    name: "Asha",\n    greet() { return this.name; },\n};\nobj.greet();              // "Asha" — method call\nconst fn = obj.greet;\n// fn();                  // undefined this — plain call'],
                    ["Arrow functions inherit this", "Arrow functions don't have their own this — they capture it from the surrounding scope. This makes them perfect for callbacks inside methods (setTimeout, array methods, event handlers) where a regular function would lose this.", 'const timer = {\n    seconds: 0,\n    start() {\n        setInterval(() => { this.seconds++; }, 1000);  // arrow keeps `this`\n    },\n};'],
                    ["call, apply, and bind", "These explicitly set this: call and apply invoke immediately (call takes arguments individually, apply as an array); bind returns a new function permanently bound to a this value — the classic fix for passing a method as a callback.", 'function greet(greeting) { return `${greeting}, ${this.name}`; }\ngreet.call({ name: "Ravi" }, "Hi");        // "Hi, Ravi"\nconst bound = greet.bind({ name: "Asha" });\nbound("Hello");                             // "Hello, Asha"'],
                ],
                ex: "Demonstrate this losing its binding when a method is passed as a callback, then fix it three ways: an arrow wrapper, bind, and defining the callback as an arrow. Use call to borrow a method for a different object.",
                tips: ["this is set by the call site, not the definition", "Arrow functions inherit this — ideal for callbacks", "call/apply invoke with a this; bind returns a bound function"],
            },
            {
                t: "ES Modules In Depth", s: "js-modules-deep",
                e: "Organize code across files with the standard module system — named, default, and dynamic imports.",
                sec: [
                    ["Named and default exports", "Export multiple values by name, or one main value as the default. Import named exports in braces (matching names) and the default with any name. A file's exports form its public API; everything else stays private to the module.", '// utils.js\nexport const TAX = 0.18;\nexport function withTax(p) { return p * (1 + TAX); }\nexport default function main() {}\n\n// app.js\nimport main, { withTax, TAX } from "./utils.js";'],
                    ["Modules are isolated and run once", "Each module has its own scope (no accidental globals), and is evaluated only once no matter how many files import it — imports are live references to the same instance. This makes shared state and singletons predictable.", 'import { renameImport as fresh } from "./x.js";   // rename on import\nimport * as utils from "./utils.js";              // namespace import\nutils.withTax(100);'],
                    ["Dynamic import and modules in the browser", "import() loads a module on demand at runtime, returning a promise — the basis of code splitting and lazy loading. In browsers, use <script type=\"module\"> (deferred by default, CORS-aware). In Node, ESM is enabled via type: module or .mjs.", 'const { default: Chart } = await import("./chart.js");   // load when needed\n// <script type="module" src="app.js"></script>'],
                ],
                ex: "Split an app into modules with a mix of named and default exports, use a namespace import and a renamed import, and lazy-load a heavy module with dynamic import() only when a button is clicked.",
                tips: ["Named exports (braces) + one default per file", "Modules are scoped and evaluated once; imports are live", "import() lazy-loads at runtime; type=module in browsers"],
            },
            {
                t: "Iterators, Generators, and Symbols", s: "js-iterators-generators",
                e: "The protocols behind for...of and spread — and generators for lazy, custom sequences.",
                sec: [
                    ["The iterable protocol", "for...of, spread, and destructuring all work on iterables — objects with a Symbol.iterator method returning an iterator (an object with next()). Arrays, strings, Sets, and Maps are built-in iterables; you can make your own objects iterable too.", 'const range = {\n    from: 1, to: 3,\n    [Symbol.iterator]() {\n        let n = this.from, last = this.to;\n        return { next: () => n <= last ? { value: n++, done: false } : { value: undefined, done: true } };\n    },\n};\nconsole.log([...range]);   // [1, 2, 3]'],
                    ["Generators", "A generator function (function*) pauses at each yield and resumes on the next call — producing values lazily, on demand. It's the easy way to create iterators and to represent infinite or expensive sequences without computing everything up front.", 'function* idMaker() {\n    let id = 1;\n    while (true) yield id++;   // infinite, but lazy\n}\nconst gen = idMaker();\ngen.next().value;   // 1\ngen.next().value;   // 2'],
                    ["Symbols", "Symbols are unique, immutable primitives used as non-colliding object keys — including 'well-known' symbols like Symbol.iterator that hook into language features. They enable metadata and protocol methods without clashing with regular string keys.", 'const id = Symbol("id");\nconst obj = { [id]: 123 };   // unique key, won\'t collide\nconsole.log(obj[id]);        // 123'],
                ],
                ex: "Make a custom object iterable with Symbol.iterator so for...of and spread work on it. Write a generator that yields the Fibonacci sequence lazily and take the first 10 values. Use a Symbol as a private-ish object key.",
                tips: ["Iterables (Symbol.iterator) power for...of, spread, destructuring", "Generators (function*/yield) produce values lazily on demand", "Symbols are unique keys for protocols and non-colliding metadata"],
            },
            {
                t: "Promises In Depth", s: "js-promises-deep",
                e: "Go beyond async/await to understand promises fully — chaining, combinators, and error flow.",
                sec: [
                    ["Creating and chaining", "A promise represents a future value: pending → fulfilled (resolve) or rejected (reject). .then transforms the result and returns a new promise, so you chain steps; a return inside then flows to the next. async/await is syntax over this machinery.", 'const wait = (ms) => new Promise(res => setTimeout(res, ms));\nfetchUser(id)\n    .then(user => fetchPosts(user.id))   // chained, sequential\n    .then(posts => console.log(posts.length))\n    .catch(err => console.error(err));'],
                    ["Combinators", "Run multiple promises together: Promise.all resolves when all succeed (rejects if any fails), Promise.allSettled waits for all and reports each outcome, Promise.race settles with the first to finish, and Promise.any resolves with the first success. Choose by how you want failures handled.", 'const [a, b] = await Promise.all([fetchA(), fetchB()]);   // both, fail-fast\nconst results = await Promise.allSettled([p1, p2, p3]);   // all, never rejects\nconst fastest = await Promise.race([primary(), timeout(5000)]);'],
                    ["Error propagation", "A rejection skips down to the nearest .catch (or is caught by try/catch with await). An unhandled rejection is a bug that can crash Node — always handle errors. Throwing inside then/async rejects the resulting promise, so errors compose naturally.", 'try {\n    const data = await Promise.all([load1(), load2()]);\n} catch (err) {\n    // any rejection lands here\n}'],
                ],
                ex: "Implement a delay(ms) promise and a timeout wrapper using Promise.race. Fetch three resources with Promise.all (fail-fast) and again with Promise.allSettled, and print how the two handle one failing request differently.",
                tips: [".then chains and returns new promises; async/await is sugar over it", "all (fail-fast), allSettled (all outcomes), race/any (first)", "Always handle rejections — unhandled ones can crash Node"],
            },
            {
                t: "Hoisting, Strict Mode, and Best Practices", s: "js-best-practices",
                e: "The execution-model quirks to know and the habits that keep JavaScript maintainable.",
                sec: [
                    ["Hoisting and the temporal dead zone", "Declarations are processed before code runs: function declarations are fully hoisted (callable before their line), while let/const are hoisted but unusable until declared (the 'temporal dead zone'), and var initializes to undefined. This explains many 'why is this undefined?' surprises.", 'greet();                       // works — function declaration hoisted\nfunction greet() {}\n// console.log(x);             // ReferenceError — TDZ\nlet x = 5;'],
                    ["Strict mode", "\"use strict\" (automatic in modules and classes) turns silent mistakes into errors: assigning to undeclared variables, duplicate parameters, and unsafe this. It makes code safer and faster to optimize — always develop in strict mode."],
                    ["Best practices and common mistakes", "Habits that pay off: const by default, === over ==, small pure functions, meaningful names, avoid global variables, handle errors, and don't mutate shared data. Common bugs: forgetting await, off-by-one loops, this binding loss, and floating-point comparisons. A linter (ESLint) and formatter (Prettier) catch many automatically."],
                ],
                ex: "Demonstrate hoisting differences between a function declaration, var, and let (including a TDZ error). Then take a small messy script and refactor it applying the best practices: const, ===, extracted pure functions, and error handling.",
                tips: ["Function declarations hoist fully; let/const have a TDZ", "Strict mode (default in modules) turns silent bugs into errors", "const/===/small pure functions/no globals; lint and format"],
            },
        ],
    },
}
