// Python Programming course — 3 levels × 3 lessons.
// Lesson: t=title, s=slug, e=lead, sec=[heading, paragraph, code?][], ex=exercise, tips=[...]

export const PYTHON = {
    name: "Python Programming",
    palette: ["#3776ab", "#ffd43b"],
    kw: "python,programming",
    images: ["1526379095098-d400fd0bf935", "1555949963-aa79dcee981c", "1515879218367-8466d910aaa4"],
    levels: {
        Basic: [
            {
                t: "Getting Started: Your First Python Program", s: "getting-started-first-program",
                e: "Install Python, run your first program, and understand what actually happens when you execute code.",
                sec: [
                    ["Installing Python the right way", "Download Python from python.org (3.12 or newer) and, on Windows, tick 'Add Python to PATH' during installation. Verify with `python --version` in a terminal. On macOS and Linux, Python is often preinstalled — but install a current version anyway, since system Python can be years old.", "python --version\n# Python 3.12.4"],
                    ["Hello, World — and what it means", "Create a file called hello.py, write one line, and run it with `python hello.py`. The print() function sends text to the screen. That's the whole loop of programming: you write instructions, the interpreter executes them top to bottom, and you observe the result.", 'print("Hello, World!")\nprint("Python is running my instructions, line by line.")'],
                    ["Variables: naming your data", "A variable is a name attached to a value. Python figures out the type on its own — text (str), whole numbers (int), decimals (float), and True/False (bool). Use lowercase names with underscores, and pick names that describe the contents.", 'name = "Asha"\nage = 24\nheight_m = 1.62\nis_student = True\nprint(f"{name} is {age} years old")'],
                ],
                ex: "Write a program that stores your name, your birth year, and computes your age this year, then prints a sentence like 'Asha is 24 this year'. Use an f-string for the output.",
                tips: ["Python executes files top to bottom", "print() displays values; f-strings embed variables in text", "Variables get their type from the value you assign"],
            },
            {
                t: "Making Decisions: Conditions and Loops", s: "conditions-and-loops",
                e: "Programs become useful the moment they can decide and repeat. Master if/elif/else, for, and while.",
                sec: [
                    ["Branching with if / elif / else", "Conditions let code react to data. Python uses indentation (4 spaces) instead of braces — the indented block belongs to the condition above it. Comparison operators: ==, !=, <, >, <=, >=, plus and/or/not to combine them.", 'marks = 78\nif marks >= 90:\n    grade = "A"\nelif marks >= 75:\n    grade = "B"\nelse:\n    grade = "C"\nprint(grade)  # B'],
                    ["Repeating with for loops", "A for loop walks through a sequence one item at a time. range(n) generates numbers 0 to n-1 — the workhorse of counted repetition. You'll use for loops on lists, strings, files, and query results constantly.", 'for i in range(3):\n    print("run", i)\n\nfor letter in "abc":\n    print(letter.upper())'],
                    ["while loops and break", "A while loop repeats as long as a condition stays true — ideal when you don't know the iteration count in advance, like waiting for valid input. Use break to exit early and continue to skip to the next round; beware conditions that never become false.", 'count = 0\nwhile True:\n    count += 1\n    if count == 5:\n        break\nprint("stopped at", count)'],
                ],
                ex: "Write a number-guessing game: pick a secret number, loop asking the user for guesses with input(), print 'higher' or 'lower' hints, and break with a success message when they get it.",
                tips: ["Indentation defines blocks — be consistent", "for iterates sequences; while repeats on a condition", "break exits a loop, continue skips one iteration"],
            },
            {
                t: "Lists, Dictionaries, and Functions", s: "lists-dicts-functions",
                e: "The three constructs you'll use in every real Python program: collections for data, functions for structure.",
                sec: [
                    ["Lists: ordered collections", "A list holds items in order and can grow and shrink. Index from 0, slice with [start:end], append to add, and use len() for the count. Lists are the default container for 'many things' in Python.", 'fruits = ["apple", "mango", "banana"]\nfruits.append("kiwi")\nprint(fruits[0])      # apple\nprint(fruits[-1])     # kiwi\nprint(fruits[1:3])    # [\'mango\', \'banana\']'],
                    ["Dictionaries: labeled data", "A dict maps keys to values — like a real dictionary maps words to meanings. Perfect for structured records: fast lookup by key, .get() for safe access with a default, and .items() to loop over pairs.", 'user = {"name": "Ravi", "age": 30}\nprint(user["name"])          # Ravi\nprint(user.get("city", "?")) # ?\nfor key, value in user.items():\n    print(key, "→", value)'],
                    ["Functions: reusable logic", "A function packages steps behind a name. Parameters bring data in, return sends results out. Default values make arguments optional. If you copy-paste code twice, it should probably be a function.", 'def greet(name, lang="en"):\n    if lang == "hi":\n        return f"Namaste, {name}!"\n    return f"Hello, {name}!"\n\nprint(greet("Asha"))\nprint(greet("Asha", lang="hi"))'],
                ],
                ex: "Build a tiny contact book: a list of dicts with name and phone keys. Write functions add_contact(book, name, phone) and find_contact(book, name), then demonstrate adding three contacts and finding one.",
                tips: ["Lists for ordered items, dicts for labeled fields", "Negative indexes count from the end", "Functions should do one thing and return a value"],
            },
            {
                t: "Working With Strings and Text", s: "python-strings",
                e: "Text is everywhere — names, files, user input, APIs. Master Python's rich string toolkit.",
                sec: [
                    ["Slicing and core methods", "Strings are immutable sequences you can index and slice like lists. The everyday methods: .strip() trims whitespace, .lower()/.upper() change case, .replace() swaps text, .split()/.join() convert between strings and lists, and .startswith()/.endswith() test edges.", 'raw = "  Hello, World  "\nprint(raw.strip().lower())        # hello, world\nprint("a,b,c".split(","))         # [\'a\', \'b\', \'c\']\nprint("-".join(["2024", "07"]))  # 2024-07'],
                    ["f-strings and formatting", "f-strings interpolate expressions and control presentation: :.2f for two decimals, :, for thousands separators, alignment and padding for tables. They're faster and clearer than older % or .format() styles.", 'price = 1234.5\nqty = 3\nprint(f"Total: ₹{price * qty:,.2f}")   # Total: ₹3,703.50\nprint(f"{\'Name\':<10}{\'Score\':>5}")     # left/right aligned'],
                    ["Searching and cleaning text", "Use `in` to test substrings, .find()/.index() for positions, and .count() to tally. For pattern work beyond literals — emails, phone numbers, dates — the re module brings regular expressions, the professional tool for text extraction and validation.", 'text = "Contact: asha@mail.com"\nimport re\nmatch = re.search(r"[\\w.]+@[\\w.]+", text)\nprint(match.group())   # asha@mail.com'],
                ],
                ex: "Write clean_name(raw) that trims whitespace, title-cases the words, and collapses multiple internal spaces into one — so '  john   DOE ' becomes 'John Doe'. Then write a function that extracts all email addresses from a block of text using re.",
                tips: ["Strings are immutable — methods return new strings", "f-strings with format specs handle money and tables", "Reach for re when patterns go beyond literal text"],
            },
            {
                t: "The Standard Library Toolkit", s: "python-standard-library",
                e: "Python ships 'batteries included'. Knowing what's already there saves you from reinventing (or installing) it.",
                sec: [
                    ["Dates, math, and random", "datetime handles dates and durations, math has the numeric functions, and random covers shuffling and sampling. These three cover a huge share of everyday scripting needs with zero installation.", 'from datetime import date, timedelta\nimport random\n\ntoday = date.today()\nprint(today + timedelta(days=30))     # date a month out\nprint(random.choice(["heads", "tails"]))'],
                    ["Collections and counting", "The collections module upgrades the built-ins: Counter tallies occurrences in one line, defaultdict removes 'if key not in dict' boilerplate, and namedtuple/dataclass give lightweight records. Counter alone replaces dozens of manual loops.", 'from collections import Counter\nwords = "the cat sat on the mat".split()\nprint(Counter(words).most_common(1))  # [(\'the\', 2)]'],
                    ["Paths and JSON", "pathlib makes file paths clean and cross-platform (no string gluing), and json converts between Python objects and JSON text — the lingua franca of APIs and config files.", 'from pathlib import Path\nimport json\n\nconfig = json.loads(Path("config.json").read_text())\nprint(config["setting"])'],
                ],
                ex: "Read a text file of words and use collections.Counter to print the 5 most common words longer than 3 letters. Then write the result to a JSON file using pathlib and json.",
                tips: ["Check the standard library before pip installing", "Counter and defaultdict erase counting boilerplate", "pathlib for paths, json for data interchange"],
            },
            {
                t: "Syntax, Indentation, and Comments", s: "python-syntax",
                e: "Python's defining feature — meaningful whitespace — and how to write readable code from the start.",
                sec: [
                    ["Indentation defines structure", "Unlike most languages that use braces, Python uses indentation to group code into blocks. The lines inside an if, loop, or function must be indented consistently (4 spaces is the standard). Get the indentation wrong and you get an IndentationError — the whitespace is the syntax.", 'if True:\n    print("indented — inside the if")\n    print("still inside")\nprint("outside the if")'],
                    ["Statements and line structure", "Each statement is normally its own line — no semicolons needed. A long statement can wrap across lines inside brackets, or with a backslash. Keep one idea per line for readability.", 'total = (1 + 2 +\n         3 + 4)      # wraps inside parentheses\nx = 1; y = 2           # semicolons work but are discouraged'],
                    ["Comments and docstrings", "A # begins a comment to end of line — for notes to humans, ignored by Python. A string as the first statement of a module, function, or class is a docstring: built-in documentation accessible via help() and tools.", '# This is a comment\ndef area(r):\n    """Return the area of a circle with radius r."""\n    return 3.14159 * r * r'],
                ],
                ex: "Write a small script that uses nested indentation (an if inside a loop), add explanatory comments, and give a function a docstring. Deliberately mis-indent a line to see the IndentationError, then fix it.",
                tips: ["Indentation (4 spaces) defines blocks — it IS the syntax", "One statement per line; no semicolons needed", "# for comments; a leading string is a docstring"],
            },
            {
                t: "Variables and Assignment", s: "python-variables",
                e: "How Python names values, the assignment tricks it offers, and naming conventions.",
                sec: [
                    ["Names point to values", "A variable is a name bound to a value; you never declare a type — Python infers it and lets it change. Names are case-sensitive; use lowercase_with_underscores by convention, and choose names that describe the contents.", 'age = 30\nage = "thirty"        # allowed — type can change\ntotal_price = 199.99'],
                    ["Multiple and swap assignment", "Python assigns several variables at once and swaps without a temporary variable — a clean, readable idiom used constantly.", 'x, y, z = 1, 2, 3\na = b = 0            # both set to 0\nx, y = y, x          # swap in one line'],
                    ["Constants and unpacking", "Python has no true constants — by convention, ALL_CAPS names signal 'do not change'. Unpacking assigns from any sequence, and a starred name collects the rest.", 'PI = 3.14159          # convention: treat as constant\nfirst, *middle, last = [1, 2, 3, 4, 5]\n# first=1, middle=[2,3,4], last=5'],
                ],
                ex: "Assign three variables on one line, swap two of them without a temp, unpack a list into first/rest/last with a starred name, and define an ALL_CAPS constant. Print each result.",
                tips: ["Names bind to values; type is inferred and can change", "Multiple assignment and one-line swaps are idiomatic", "ALL_CAPS by convention for constants; * unpacks the rest"],
            },
            {
                t: "Data Types and Type Casting", s: "python-data-types-casting",
                e: "Python's built-in types and how to convert between them safely.",
                sec: [
                    ["The core built-in types", "Python's essentials: int (whole numbers, unlimited size), float (decimals), str (text), bool (True/False), plus the containers list, tuple, dict, and set. Check any value's type with type() and test membership of a type with isinstance().", 'type(42)          # <class \'int\'>\ntype(3.14)        # <class \'float\'>\ntype("hi")        # <class \'str\'>\nisinstance(True, bool)   # True'],
                    ["Type casting", "Convert between types with the type names as functions: int(), float(), str(), bool(), list(), tuple(), set(). Casting a numeric string to int works; casting a non-numeric one raises ValueError, so validate or catch it.", 'int("42")         # 42\nfloat("3.14")     # 3.14\nstr(100)          # "100"\nlist("abc")       # [\'a\', \'b\', \'c\']\n# int("x")        # ValueError'],
                    ["Truthiness", "Every value is truthy or falsy in a condition. Falsy values: False, 0, 0.0, empty string, empty containers ([], {}, set()), and None. Everything else is truthy — so `if items:` neatly checks for a non-empty list.", 'if not name:            # True when name is empty/None\n    name = "Anonymous"\nbool(0), bool(""), bool([])   # all False'],
                ],
                ex: "Write a function that takes user input (a string) and safely converts it to an int, returning a default on failure. Demonstrate truthiness by handling an empty list, empty string, and None with a single `if not value` check.",
                tips: ["Core types: int, float, str, bool + list/tuple/dict/set", "Cast with int()/float()/str()/list(); bad casts raise ValueError", "Falsy: 0, empty string/containers, None — else truthy"],
            },
            {
                t: "Operators", s: "python-operators",
                e: "Every operator category Python offers — including the membership and identity operators unique to it.",
                sec: [
                    ["Arithmetic and comparison", "Arithmetic: + - * / (always float) // (floor division) % (remainder) ** (power). Comparisons (== != < > <= >=) return booleans and can be chained, a Python nicety.", '7 / 2            # 3.5\n7 // 2           # 3  (floor)\n2 ** 10          # 1024\n1 < x < 10       # chained comparison'],
                    ["Logical operators", "Python spells them out: and, or, not. They short-circuit and return an operand (not just a bool), enabling the `value or default` idiom.", 'is_admin and can_edit\nname = user_input or "Guest"    # default if falsy\nnot logged_in'],
                    ["Membership and identity", "in / not in test membership in any container or string — extremely common. is / is not test object identity (same object in memory), used mainly for None checks (always `x is None`, never `x == None`).", '"a" in ["a", "b"]        # True\n"key" in my_dict          # checks keys\nif result is None: ...     # identity check for None'],
                ],
                ex: "Write expressions using //, %, and ** ; a chained comparison to check a value is in range; the `or` default idiom; and both a membership test (`in`) and a correct None check (`is None`). Explain why == None is discouraged.",
                tips: ["/ is float division, // floors, ** powers; comparisons chain", "Logical: and/or/not — short-circuit and return operands", "in for membership; `is None` for identity (never == None)"],
            },
            {
                t: "Numbers and the Math Module", s: "python-numbers",
                e: "Work with integers, floats, and complex numbers, and compute with the math and random modules.",
                sec: [
                    ["Integers and floats", "Python integers have unlimited precision (no overflow), while floats are standard doubles with the usual rounding caveats (0.1 + 0.2 != 0.3). Underscores make big numbers readable, and round() rounds to a given number of places.", 'big = 1_000_000\n2 ** 100                 # exact, arbitrarily large\nround(3.14159, 2)        # 3.14\nround(0.1 + 0.2, 2)      # 0.3'],
                    ["The math module", "For serious math, import math: sqrt, floor, ceil, factorial, trig functions, and constants like pi and e. It operates on floats and returns precise results.", 'import math\nmath.sqrt(144)     # 12.0\nmath.floor(4.7)    # 4\nmath.factorial(5)  # 120\nmath.pi            # 3.14159...'],
                    ["Random and precise decimals", "The random module handles randomness (random, randint, choice, shuffle, sample). For money and exact decimals where float rounding is unacceptable, use the decimal module.", 'import random\nrandom.randint(1, 6)          # dice roll\nrandom.choice(["a", "b", "c"])\n\nfrom decimal import Decimal\nDecimal("0.1") + Decimal("0.2")   # exactly 0.3'],
                ],
                ex: "Compute a compound-interest figure using ** , round it to 2 places, and reproduce a float precision error then fix it with Decimal. Use random to simulate rolling two dice 1000 times and report the most common total.",
                tips: ["Ints are unlimited precision; floats round (use round())", "import math for sqrt/floor/factorial/pi and more", "random for randomness; decimal for exact money math"],
            },
            {
                t: "Tuples and Sets", s: "python-tuples-sets",
                e: "Two more essential containers beyond lists and dicts — immutable sequences and unique collections.",
                sec: [
                    ["Tuples: immutable sequences", "A tuple is like a list but immutable — once created it can't change. Use tuples for fixed groups (coordinates, records, function returns of multiple values) and as dictionary keys (lists can't be keys). Unpacking a tuple is idiomatic.", 'point = (10, 20)\nx, y = point            # unpacking\ndef minmax(nums): return (min(nums), max(nums))\nlow, high = minmax([3, 1, 9])'],
                    ["Sets: unique, unordered", "A set stores unique values with fast membership testing. Adding a duplicate does nothing, so sets deduplicate instantly. They are unordered and can't be indexed.", 'tags = {"a", "b", "a"}   # {\'a\', \'b\'}\ntags.add("c")\n"a" in tags               # fast membership\nunique = set([1, 1, 2, 3]) # {1, 2, 3}'],
                    ["Set operations", "Sets support mathematical operations — union (|), intersection (&), difference (-), symmetric difference (^) — making them ideal for comparing collections: common elements, what's missing, what's shared.", 'a = {1, 2, 3}; b = {2, 3, 4}\na & b        # {2, 3}  intersection\na | b        # {1, 2, 3, 4}  union\na - b        # {1}  difference'],
                ],
                ex: "Return multiple values from a function as a tuple and unpack them. Deduplicate a list with a set. Given two lists of tags, use set operations to find tags in both, tags only in the first, and all unique tags.",
                tips: ["Tuples are immutable — for fixed records and dict keys", "Sets hold unique values with fast membership and dedupe", "Set math: & intersection, | union, - difference, ^ symmetric"],
            },
            {
                t: "Booleans, Conditionals, and match", s: "python-booleans-match",
                e: "Deepen decision-making with boolean logic, the conditional expression, and the modern match statement.",
                sec: [
                    ["Booleans and comparison chains", "Booleans (True/False) come from comparisons and logical operators. Python lets you chain comparisons naturally, and any() / all() test whole iterables of conditions at once.", 'nums = [2, 4, 6]\nall(n % 2 == 0 for n in nums)   # True — all even\nany(n > 5 for n in nums)        # True\n0 <= score <= 100               # chained'],
                    ["Conditional expressions", "Python's ternary reads like English: value_if_true if condition else value_if_false. It's an expression, so it produces a value you can assign or pass directly.", 'label = "even" if n % 2 == 0 else "odd"\nprint("pass" if score >= 40 else "fail")'],
                    ["The match statement", "Python 3.10+ adds match/case — structural pattern matching that's cleaner than long if/elif chains and can destructure values. Use | for multiple patterns and _ as the catch-all.", 'match command.split():\n    case ["go", direction]:\n        move(direction)\n    case ["quit"] | ["exit"]:\n        stop()\n    case _:\n        print("Unknown command")'],
                ],
                ex: "Use all()/any() to validate that a list of form fields are all filled. Assign a grade label with a conditional expression. Write a match statement that handles several command shapes, including destructuring and a catch-all.",
                tips: ["Comparisons chain; any()/all() test iterables of conditions", "Conditional expression: A if cond else B (produces a value)", "match/case (3.10+) beats long if/elif and can destructure"],
            },
            {
                t: "Input and Output Formatting", s: "python-input-output",
                e: "Read from the user and produce polished, formatted output with f-strings.",
                sec: [
                    ["Reading input", "input() reads a line from the user as a string — always cast it to the type you need. Provide a prompt argument, and validate or catch conversion errors.", 'name = input("Your name: ")\nage = int(input("Your age: "))     # cast to int\nprint(f"Hi {name}, next year you\'ll be {age + 1}")'],
                    ["f-string formatting", "f-strings embed expressions in {} and support format specifiers after a colon: .2f for two decimals, , for thousands separators, alignment (<, >, ^) with a width, and even = for debugging (prints name=value).", 'price = 1234.5\nprint(f"Total: {price:,.2f}")      # Total: 1,234.50\nprint(f"{\'Name\':<10}{\'Score\':>6}") # aligned columns\nx = 5; print(f"{x=}")              # x=5'],
                    ["print options and files", "print() takes sep and end arguments to control separators and line endings, and a file argument to write elsewhere. Combine with formatting for clean reports and tables.", 'print("a", "b", "c", sep=" | ")   # a | b | c\nprint("no newline", end="")\nfor i in range(1, 4):\n    print(f"{i:>3} {i**2:>5}")     # right-aligned table'],
                ],
                ex: "Write an interactive program that asks for a name and a budget, validates the budget as a number, and prints a formatted summary using f-string alignment and thousands separators. Print a small right-aligned multiplication table.",
                tips: ["input() returns a string — cast it (int/float) as needed", "f-string specs: :.2f, :, thousands, alignment, {x=} debug", "print() sep/end/file control separators, endings, destination"],
            },
        ],
        Intermediate: [
            {
                t: "Files, Errors, and Modules", s: "files-errors-modules",
                e: "Real programs read files, survive bad input, and split across modules. Level up from scripts to software.",
                sec: [
                    ["Reading and writing files", "Use the with statement — it opens the file and guarantees it closes, even on errors. Read whole files with .read(), line by line with a for loop, and write with mode 'w' (overwrite) or 'a' (append).", 'with open("notes.txt", "w") as f:\n    f.write("first line\\n")\n\nwith open("notes.txt") as f:\n    for line in f:\n        print(line.strip())'],
                    ["Handling errors with try/except", "Crashes come from the unexpected: missing files, bad numbers, network failures. Wrap risky code in try, catch the specific exception you expect, and always avoid a bare except that hides real bugs. finally runs no matter what.", 'try:\n    age = int(input("Age: "))\nexcept ValueError:\n    print("That is not a number")\nelse:\n    print("You are", age)'],
                    ["Modules and pip", "Split code into files and import between them — a file named utils.py is imported as `import utils`. The standard library covers dates, JSON, paths, and more; everything else installs with pip inside a virtual environment (python -m venv .venv) so projects don't fight over versions.", 'import json\nfrom datetime import date\n\ndata = {"day": str(date.today())}\nprint(json.dumps(data))'],
                ],
                ex: "Write a program that reads a text file of one number per line, ignores lines that aren't numbers (using try/except), and writes the total and average to results.txt.",
                tips: ["Always open files with `with`", "Catch specific exceptions, never bare except", "One virtual environment per project"],
            },
            {
                t: "Object-Oriented Python", s: "object-oriented-python",
                e: "Classes bundle data with the functions that operate on it — the pattern behind almost every Python library you'll use.",
                sec: [
                    ["Classes and instances", "A class is a blueprint; each object built from it is an instance with its own data. __init__ runs at creation and stores attributes on self. Methods are functions that automatically receive the instance as self.", 'class BankAccount:\n    def __init__(self, owner, balance=0):\n        self.owner = owner\n        self.balance = balance\n\n    def deposit(self, amount):\n        self.balance += amount\n        return self.balance\n\nacc = BankAccount("Asha")\nacc.deposit(500)\nprint(acc.balance)  # 500'],
                    ["Inheritance and overriding", "A subclass inherits everything from its parent and can override or extend behavior. Use super() to call the parent's version. Prefer shallow hierarchies — one level of inheritance solves most real problems.", 'class SavingsAccount(BankAccount):\n    def __init__(self, owner, balance=0, rate=0.04):\n        super().__init__(owner, balance)\n        self.rate = rate\n\n    def add_interest(self):\n        self.balance *= (1 + self.rate)'],
                    ["Dunder methods make objects feel native", "Special methods like __str__ (printing), __eq__ (==), and __len__ (len()) let your objects work with Python's built-in syntax. Implementing a few of these is what makes a class pleasant to use.", 'class Playlist:\n    def __init__(self, songs):\n        self.songs = songs\n    def __len__(self):\n        return len(self.songs)\n    def __str__(self):\n        return f"Playlist({len(self)} songs)"\n\nprint(Playlist(["a", "b"]))  # Playlist(2 songs)'],
                ],
                ex: "Model a library: a Book class (title, author, available) and a Library class holding books with methods borrow(title) and return_book(title) that flip availability and refuse to lend an unavailable book.",
                tips: ["__init__ + self store per-instance data", "Override methods in subclasses; call super() when extending", "__str__ and friends integrate objects with built-ins"],
            },
            {
                t: "Comprehensions, Generators, and Pythonic Style", s: "pythonic-style",
                e: "Write the Python that experienced developers write: expressive one-liners, lazy iteration, and clean idioms.",
                sec: [
                    ["List and dict comprehensions", "Comprehensions build collections in one readable expression: transform + filter in a single line. They replace three-line loop-and-append patterns and usually run faster too. Keep them to one condition — beyond that, use a normal loop.", 'nums = [1, 2, 3, 4, 5, 6]\nsquares = [n * n for n in nums]\nevens = [n for n in nums if n % 2 == 0]\nby_name = {n: len(n) for n in ["asha", "ravi"]}'],
                    ["Generators: lazy sequences", "A generator produces values one at a time, on demand, using yield — so you can process millions of items without loading them into memory. Any function with yield becomes a generator; generator expressions use () instead of [].", 'def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\n\nfor x in countdown(3):\n    print(x)   # 3 2 1\n\ntotal = sum(n * n for n in range(1_000_000))'],
                    ["Idioms that mark clean Python", "Unpack tuples (a, b = b, a), enumerate instead of manual counters, zip to walk lists together, and truthiness instead of comparing to empty. Run your code through a formatter (black) and a linter (ruff) — consistency is a feature.", 'names = ["Asha", "Ravi"]\nscores = [91, 84]\nfor i, (name, score) in enumerate(zip(names, scores), 1):\n    print(f"{i}. {name}: {score}")'],
                ],
                ex: "Given a list of dicts representing orders (each with 'amount' and 'status'), use one comprehension to get amounts of all 'paid' orders, sum them with a generator expression, and print the total.",
                tips: ["Comprehensions: transform + filter in one line", "yield turns a function into a memory-friendly generator", "enumerate and zip beat manual index juggling"],
            },
            {
                t: "Dataclasses and Type Hints", s: "python-dataclasses-typing",
                e: "Write self-documenting Python that tools can check: typed function signatures and clean data records.",
                sec: [
                    ["Type hints", "Annotations state intent and let editors and mypy catch mismatches before runtime. Hint the boundaries — parameters and returns — and let inference cover locals. They don't affect execution; they're a safety net and living documentation.", 'def total(prices: list[float], tax: float = 0.18) -> float:\n    return sum(prices) * (1 + tax)'],
                    ["Dataclasses", "@dataclass generates __init__, __repr__, and __eq__ from typed fields — records without boilerplate. Defaults, ordering, and immutability (frozen=True) come free, making them ideal for the small structured objects that litter real code.", 'from dataclasses import dataclass\n\n@dataclass\nclass Product:\n    name: str\n    price: float\n    in_stock: bool = True\n\np = Product("Pen", 40)\nprint(p)   # Product(name=\'Pen\', price=40, in_stock=True)'],
                    ["Optionals and unions", "Model 'maybe missing' with `X | None` and alternatives with unions. Combined with a checker, this eliminates whole bug classes — the forgotten None that crashes in production becomes an error in your editor.", 'def find_user(uid: int) -> "User | None":\n    return db.get(uid)  # caller is forced to handle None'],
                ],
                ex: "Model a shopping cart with dataclasses: a CartItem (name, price, qty) and a Cart holding a list of them, with a typed total() method and an add(item) method. Add type hints throughout and run mypy.",
                tips: ["Type the boundaries, infer the rest", "@dataclass removes record boilerplate", "X | None forces callers to handle absence"],
            },
            {
                t: "Virtual Environments, pip, and Project Structure", s: "python-project-structure",
                e: "Move from single scripts to real projects: isolated dependencies, sane layout, and reproducible installs.",
                sec: [
                    ["Virtual environments", "Each project gets its own isolated set of packages so versions never collide. Create with `python -m venv .venv`, activate it, and install into it — never into system Python. Freeze exact versions for reproducibility.", 'python -m venv .venv\nsource .venv/bin/activate      # Windows: .venv\\Scripts\\activate\npip install requests\npip freeze > requirements.txt'],
                    ["Project layout", "A predictable structure scales: source in a package folder, tests alongside, config in pyproject.toml, secrets in a .gitignored .env. This is what makes a project navigable by others (and future you).", '# project/\n#   myapp/__init__.py\n#   myapp/core.py\n#   tests/test_core.py\n#   pyproject.toml\n#   .env  (gitignored)'],
                    ["Imports and __main__", "Understand absolute imports within your package, and the `if __name__ == \"__main__\":` guard that lets a file be both importable and runnable — the idiom behind every well-behaved Python script.", 'def main():\n    print("run directly")\n\nif __name__ == "__main__":\n    main()'],
                ],
                ex: "Restructure your earlier contact-book script into a proper project: a package folder with the logic, a __main__ guard for the CLI, a requirements.txt, and a .gitignore excluding .venv and .env.",
                tips: ["One virtual environment per project, always", "Pin versions with requirements.txt or a lockfile", "The __main__ guard makes files import- and run-safe"],
            },
            {
                t: "Lambdas and Functional Tools", s: "python-lambda-functional",
                e: "Small anonymous functions and the built-ins that transform data with them.",
                sec: [
                    ["Lambda functions", "A lambda is a one-line anonymous function — useful as a short throwaway passed to another function. Keep them tiny; if a lambda gets complex, use a named def instead for readability.", 'square = lambda x: x * x\nsquare(5)                 # 25\n# typically used inline, not assigned:\nsorted(words, key=lambda w: len(w))'],
                    ["map, filter, and sorted keys", "map applies a function to every item, filter keeps items passing a test, and sorted/min/max accept a key function to sort or select by a computed value. Lambdas make these concise.", 'nums = [1, 2, 3, 4]\nlist(map(lambda n: n * 2, nums))       # [2,4,6,8]\nlist(filter(lambda n: n % 2, nums))    # [1,3]\nmax(people, key=lambda p: p["age"])'],
                    ["Comprehensions often win", "In Python, a comprehension is usually clearer than map/filter with a lambda — `[n*2 for n in nums]` reads better than the map version. Reach for map/filter mainly when passing an existing named function.", '[n * 2 for n in nums]                  # clearer than map\n[n for n in nums if n % 2]             # clearer than filter\nlist(map(str.upper, ["a", "b"]))       # named function: map is fine'],
                ],
                ex: "Sort a list of dicts by a nested field using a lambda key. Rewrite a map+lambda and a filter+lambda as comprehensions. Use max with a key to find the longest word in a list.",
                tips: ["Lambdas are tiny inline functions — keep them small", "map/filter/sorted take a key function; lambdas fit inline", "Prefer comprehensions over map/filter+lambda for clarity"],
            },
            {
                t: "Function Arguments in Depth", s: "python-args-kwargs",
                e: "Master positional, keyword, default, and variadic arguments — and the traps to avoid.",
                sec: [
                    ["Positional, keyword, and defaults", "Arguments can be passed by position or by name (keyword). Default values make parameters optional; keyword arguments improve readability at the call site and let you skip earlier optionals.", 'def greet(name, greeting="Hello", punct="!"):\n    return f"{greeting}, {name}{punct}"\ngreet("Asha")                       # Hello, Asha!\ngreet("Ravi", punct=".")            # skip greeting by name'],
                    ["*args and **kwargs", "*args collects extra positional arguments into a tuple; **kwargs collects extra keyword arguments into a dict. Together they let a function accept any number of arguments — and let you forward arguments to another function with * and **.", 'def log(*args, **kwargs):\n    print("positional:", args)\n    print("keyword:", kwargs)\nlog(1, 2, level="warn")\n# positional: (1, 2)   keyword: {\'level\': \'warn\'}'],
                    ["The mutable default trap", "A classic bug: a mutable default (like []) is created once and shared across all calls, accumulating values. Use None as the default and create the object inside the function.", 'def bad(items=[]):        # BUG: shared across calls\n    items.append(1); return items\n\ndef good(items=None):     # correct\n    if items is None: items = []\n    items.append(1); return items'],
                ],
                ex: "Write a function accepting a required arg, a defaulted arg, *args, and **kwargs, and call it several ways. Forward *args/**kwargs to another function. Reproduce the mutable-default bug and fix it with the None pattern.",
                tips: ["Keyword args and defaults make calls readable and flexible", "*args → tuple of extras; **kwargs → dict of extras; forward with */**", "Never use a mutable default — use None and create inside"],
            },
            {
                t: "Inheritance and Polymorphism", s: "python-oop-inheritance",
                e: "Build class hierarchies with inheritance, super(), and Python's duck typing.",
                sec: [
                    ["Inheritance and super()", "A subclass inherits a parent's attributes and methods, adding or overriding its own. Call super().__init__() to run the parent's constructor, and super().method() to extend rather than replace behavior.", 'class Animal:\n    def __init__(self, name): self.name = name\n    def speak(self): return "..."\n\nclass Dog(Animal):\n    def speak(self): return f"{self.name} barks"'],
                    ["Polymorphism and duck typing", "Different classes can define the same method, so code can call it without knowing the exact type — 'if it walks like a duck.' Python doesn't require a shared base class; it just needs the method to exist.", 'def describe(animal):\n    return animal.speak()      # works for any object with speak()\nfor a in [Dog("Rex"), Cat("Milo")]:\n    print(describe(a))'],
                    ["Abstract base classes", "When you want to require subclasses to implement certain methods, use abc.ABC with @abstractmethod — instantiating a subclass that hasn't implemented them raises an error, enforcing the contract.", 'from abc import ABC, abstractmethod\nclass Shape(ABC):\n    @abstractmethod\n    def area(self): ...\nclass Circle(Shape):\n    def __init__(self, r): self.r = r\n    def area(self): return 3.14159 * self.r ** 2'],
                ],
                ex: "Build a Shape ABC with an abstract area(), then Circle and Rectangle subclasses. Write a function that totals the areas of a mixed list of shapes (polymorphism). Use super() in a subclass constructor that adds a field.",
                tips: ["Subclasses inherit and override; super() extends the parent", "Duck typing: call a method if it exists, no shared base needed", "abc.ABC + @abstractmethod enforce a required interface"],
            },
            {
                t: "Dunder Methods and Operator Overloading", s: "python-dunder-methods",
                e: "Make your objects behave like built-ins by implementing Python's special methods.",
                sec: [
                    ["String representations", "__str__ controls how an object prints (user-facing), and __repr__ its developer/debug representation (aim to make it unambiguous). Defining these makes your objects readable everywhere.", 'class Money:\n    def __init__(self, amount): self.amount = amount\n    def __str__(self): return f"₹{self.amount:.2f}"\n    def __repr__(self): return f"Money({self.amount})"'],
                    ["Operator overloading", "Special methods let operators work on your objects: __add__ for +, __eq__ for ==, __lt__ for < (enables sorting), and more. Implement them so your types compose naturally with Python syntax.", 'class Vector:\n    def __init__(self, x, y): self.x, self.y = x, y\n    def __add__(self, o): return Vector(self.x + o.x, self.y + o.y)\n    def __eq__(self, o): return (self.x, self.y) == (o.x, o.y)'],
                    ["Container and iteration methods", "__len__ makes len() work, __getitem__ enables indexing and iteration, and __contains__ powers the in operator. Implementing a few turns a custom class into a first-class Python container.", 'class Playlist:\n    def __init__(self, songs): self.songs = songs\n    def __len__(self): return len(self.songs)\n    def __getitem__(self, i): return self.songs[i]\n# len(pl), pl[0], and for s in pl: all work'],
                ],
                ex: "Build a Vector class supporting +, ==, and a readable __repr__. Build a small collection class implementing __len__ and __getitem__ so len(), indexing, and a for loop all work on it.",
                tips: ["__str__ (user) and __repr__ (debug) control printing", "__add__/__eq__/__lt__ overload operators for your types", "__len__/__getitem__/__contains__ make custom containers"],
            },
            {
                t: "Iterators and Generators", s: "python-iterators-generators",
                e: "Produce sequences lazily and understand the protocol behind every for loop.",
                sec: [
                    ["The iterator protocol", "A for loop calls iter() to get an iterator, then next() repeatedly until StopIteration. Any object implementing __iter__ and __next__ is iterable — lists, files, and ranges all follow this protocol.", 'nums = [1, 2, 3]\nit = iter(nums)\nnext(it)      # 1\nnext(it)      # 2'],
                    ["Generators with yield", "A function using yield is a generator: it produces values one at a time, pausing between them, so it uses almost no memory even for huge or infinite sequences. Each call to next() resumes after the last yield.", 'def countdown(n):\n    while n > 0:\n        yield n\n        n -= 1\nfor x in countdown(3): print(x)   # 3 2 1\n\ndef naturals():           # infinite, but lazy\n    n = 1\n    while True: yield n; n += 1'],
                    ["Generator expressions", "Like a list comprehension but with parentheses, a generator expression produces items lazily — perfect for feeding sum(), any(), or a loop over millions of items without building a list in memory.", 'total = sum(n * n for n in range(1_000_000))   # no giant list\nany(x.isupper() for x in text)\nlines = (line.strip() for line in open("big.txt"))'],
                ],
                ex: "Write a generator that yields the Fibonacci sequence lazily and take the first 10 values. Use a generator expression to sum the squares of a million numbers without building a list. Explain the memory difference versus a list comprehension.",
                tips: ["for uses iter()/next() until StopIteration", "yield makes a generator — lazy, memory-friendly, even infinite", "Generator expressions (parens) stream into sum/any/loops"],
            },
            {
                t: "Regular Expressions with re", s: "python-regex",
                e: "Search, validate, and extract text patterns using Python's re module.",
                sec: [
                    ["Searching and matching", "The re module finds patterns in text: re.search finds the first match anywhere, re.match checks the start, re.findall returns all matches, and re.finditer yields match objects. Use raw strings (r'...') for patterns so backslashes are literal.", 'import re\nm = re.search(r"\\d+", "order 12 of 30")\nm.group()                 # "12"\nre.findall(r"\\d+", "a1b22c333")   # [\'1\', \'22\', \'333\']'],
                    ["Groups and named groups", "Parentheses create capture groups you extract by number; (?P<name>...) creates named groups for readability. This is how you pull structured pieces out of text like dates or log lines.", 'm = re.search(r"(?P<y>\\d{4})-(?P<m>\\d{2})-(?P<d>\\d{2})", "2026-01-15")\nm.group("y"), m.group("m")   # ("2026", "01")'],
                    ["Substitution and compiling", "re.sub replaces matches (with a string using \\1 backreferences or a function). Compile a pattern with re.compile when reusing it for speed and clarity. Common uses: validation, cleaning text, and reformatting.", 're.sub(r"\\s+", " ", messy)          # collapse whitespace\nre.sub(r"(\\d+)-(\\d+)", r"\\2/\\1", s)   # reorder with backrefs\nemail_re = re.compile(r"^[\\w.]+@[\\w.]+\\.\\w+$")'],
                ],
                ex: "Write regexes to validate an email, extract all hashtags from text with findall, pull year/month/day from a date using named groups, and collapse repeated whitespace with re.sub. Compile the email pattern for reuse.",
                tips: ["Use raw strings r'...'; search/match/findall/finditer to find", "Groups (…) extract pieces; (?P<name>…) names them", "re.sub replaces (with \\1 or a function); compile for reuse"],
            },
            {
                t: "Dates and Times", s: "python-datetime",
                e: "Handle dates, times, durations, and formatting with the datetime module.",
                sec: [
                    ["Creating and reading", "The datetime module provides date, time, datetime, and timedelta. datetime.now() is the current moment; construct specific ones from parts, and read components as attributes.", 'from datetime import datetime, date, timedelta\nnow = datetime.now()\nd = date(2026, 1, 15)\nnow.year, now.month, now.hour'],
                    ["Formatting and parsing", "strftime formats a datetime into a string with directives (%Y year, %m month, %d day, %H hour, %M minute); strptime parses a string back into a datetime. Use ISO format for storage and interchange.", 'now.strftime("%Y-%m-%d %H:%M")      # "2026-01-15 09:30"\ndatetime.strptime("2026-01-15", "%Y-%m-%d")\nnow.isoformat()                     # standard machine format'],
                    ["Date arithmetic and time zones", "timedelta represents durations you add or subtract; subtracting two datetimes gives a timedelta. For correctness across regions, use timezone-aware datetimes (datetime.now(timezone.utc)) rather than naive local times.", 'from datetime import timezone\ntomorrow = now + timedelta(days=1)\nage_days = (date.today() - date(2000, 1, 1)).days\nutc_now = datetime.now(timezone.utc)'],
                ],
                ex: "Write functions: format a datetime as 'Jan 15, 2026', parse a 'DD/MM/YYYY' string into a date, compute days until a future date with timedelta, and get the current UTC time as an ISO string.",
                tips: ["datetime/date/time/timedelta cover most needs", "strftime formats, strptime parses; isoformat for storage", "timedelta for arithmetic; use timezone-aware for correctness"],
            },
            {
                t: "Working with JSON and CSV", s: "python-json-csv",
                e: "Read and write the two most common data-interchange formats with the standard library.",
                sec: [
                    ["JSON", "The json module converts between Python objects and JSON text: json.dumps serializes to a string (indent for pretty output), json.loads parses a string, and json.dump/json.load work directly with files. Dicts, lists, strings, numbers, booleans, and None map cleanly.", 'import json\ntext = json.dumps({"name": "Asha", "roles": ["admin"]}, indent=2)\ndata = json.loads(text)\nwith open("config.json") as f:\n    config = json.load(f)'],
                    ["CSV", "The csv module reads and writes comma-separated data. csv.DictReader gives each row as a dict keyed by the header — far cleaner than splitting strings — and csv.DictWriter writes rows from dicts, handling quoting and commas correctly.", 'import csv\nwith open("data.csv") as f:\n    for row in csv.DictReader(f):\n        print(row["name"], row["score"])\n\nwith open("out.csv", "w", newline="") as f:\n    w = csv.DictWriter(f, fieldnames=["name", "score"])\n    w.writeheader(); w.writerow({"name": "A", "score": 90})'],
                    ["Choosing and combining", "Use JSON for nested/structured data and APIs; use CSV for tabular data and spreadsheets. A common task is converting between them — read a CSV with DictReader and dump the list of dicts as JSON, or vice versa.", 'rows = list(csv.DictReader(open("data.csv")))\njson.dump(rows, open("data.json", "w"), indent=2)'],
                ],
                ex: "Read a CSV of records with DictReader, filter rows by a condition, and write the result to a new JSON file. Then reverse it: load a JSON array of objects and write it out as a CSV with DictWriter.",
                tips: ["json.dumps/loads for strings, dump/load for files", "csv.DictReader/DictWriter treat rows as dicts by header", "JSON for nested/API data, CSV for tabular; convert between them"],
            },
        ],
        Advanced: [
            {
                t: "Decorators and Context Managers", s: "decorators-context-managers",
                e: "The two constructs behind Python's most elegant APIs — and behind frameworks like Flask and pytest.",
                sec: [
                    ["Functions are objects", "Python functions can be stored in variables, passed as arguments, and returned from other functions. That's the foundation: a decorator is just a function that takes a function and returns an enhanced replacement.", 'def shout(func):\n    def wrapper(*args, **kwargs):\n        result = func(*args, **kwargs)\n        return result.upper()\n    return wrapper\n\n@shout\ndef greet(name):\n    return f"hello {name}"\n\nprint(greet("asha"))  # HELLO ASHA'],
                    ["Practical decorators: timing and caching", "Decorators shine for cross-cutting concerns — logging, timing, retries, authentication — applied without touching the function body. The standard library ships ready ones: functools.lru_cache memoizes expensive calls in one line. Use functools.wraps inside your own to preserve the function's name and docs.", 'import functools, time\n\ndef timed(func):\n    @functools.wraps(func)\n    def wrapper(*a, **kw):\n        start = time.perf_counter()\n        result = func(*a, **kw)\n        print(f"{func.__name__}: {time.perf_counter()-start:.3f}s")\n        return result\n    return wrapper'],
                    ["Context managers beyond files", "Anything with setup/teardown fits the with statement: locks, database transactions, temporary directories, timers. Write your own trivially with contextlib.contextmanager — code before yield is setup, after is guaranteed cleanup.", 'from contextlib import contextmanager\n\n@contextmanager\ndef transaction(db):\n    db.begin()\n    try:\n        yield db\n        db.commit()\n    except Exception:\n        db.rollback()\n        raise'],
                ],
                ex: "Write a @retry(times=3) decorator factory that re-runs a failing function up to N times with a short delay, re-raising the last exception if all attempts fail. Test it on a function that fails randomly.",
                tips: ["A decorator wraps a function with extra behavior", "functools.wraps preserves metadata; lru_cache is free performance", "with = guaranteed setup/teardown for any resource"],
            },
            {
                t: "Concurrency: Threads, Processes, and asyncio", s: "python-concurrency",
                e: "Make Python fast where it matters: know which of the three concurrency models fits your workload.",
                sec: [
                    ["The GIL and choosing a model", "CPython's Global Interpreter Lock means only one thread executes Python bytecode at a time. The rule of thumb: I/O-bound work (network, disk) → threads or asyncio; CPU-bound work (math, parsing) → multiprocessing, which sidesteps the GIL with separate processes."],
                    ["ThreadPoolExecutor for easy parallel I/O", "For 'do these 50 downloads faster', concurrent.futures is the highest-value API: submit tasks to a pool and collect results. Threads share memory, so guard shared mutable state — or better, avoid sharing by returning values.", 'from concurrent.futures import ThreadPoolExecutor\nimport urllib.request\n\ndef fetch(url):\n    with urllib.request.urlopen(url, timeout=10) as r:\n        return url, r.status\n\nurls = ["https://example.com"] * 5\nwith ThreadPoolExecutor(max_workers=5) as pool:\n    for url, status in pool.map(fetch, urls):\n        print(status, url)'],
                    ["asyncio: cooperative concurrency", "async/await handles thousands of simultaneous connections on a single thread by switching tasks at every await point. It requires async libraries end to end (aiohttp, asyncpg) — one blocking call stalls the entire event loop.", 'import asyncio\n\nasync def work(n):\n    await asyncio.sleep(1)\n    return n * n\n\nasync def main():\n    results = await asyncio.gather(*(work(i) for i in range(5)))\n    print(results)\n\nasyncio.run(main())  # finishes in ~1s, not 5'],
                ],
                ex: "Take a list of 10 URLs and time three versions of fetching them: sequential, ThreadPoolExecutor with 10 workers, and asyncio with aiohttp. Print the three durations and explain the difference in a comment.",
                tips: ["I/O-bound → threads/asyncio; CPU-bound → processes", "ThreadPoolExecutor.map is the easy 80% solution", "In asyncio, one blocking call blocks everything"],
            },
            {
                t: "Testing, Typing, and Packaging Like a Professional", s: "testing-typing-packaging",
                e: "The habits that separate scripts from software: automated tests, type hints, and shippable packages.",
                sec: [
                    ["pytest: tests that pay rent", "pytest discovers any function named test_* and makes assertions plain: just assert. Parametrize to cover many cases in one test, and fixtures to share setup. A test suite is what lets you refactor without fear.", 'import pytest\nfrom mymath import divide\n\n@pytest.mark.parametrize("a,b,expected", [(10, 2, 5), (9, 3, 3)])\ndef test_divide(a, b, expected):\n    assert divide(a, b) == expected\n\ndef test_divide_by_zero():\n    with pytest.raises(ZeroDivisionError):\n        divide(1, 0)'],
                    ["Type hints and mypy", "Annotations document intent and let tools catch bugs before runtime: mismatched arguments, forgotten Nones, wrong returns. Start at function boundaries — parameters and returns — and let inference handle locals. Run mypy (or pyright) in CI.", 'def parse_price(raw: str, currency: str = "INR") -> float | None:\n    try:\n        return float(raw.replace(",", ""))\n    except ValueError:\n        return None'],
                    ["Packaging with pyproject.toml", "Modern packaging is one declarative file: metadata, dependencies, and entry points in pyproject.toml. `pip install -e .` gives you an editable install for development; `python -m build` produces wheels you can publish or ship internally.", '[project]\nname = "pricetools"\nversion = "0.1.0"\ndependencies = ["requests>=2.31"]\n\n[project.scripts]\nprice = "pricetools.cli:main"'],
                ],
                ex: "Take your contact-book exercise from the Basic level, add type hints to every function, write five pytest tests (including one edge case with pytest.raises), and package it with pyproject.toml so `pip install -e .` works.",
                tips: ["If it isn't tested, it's broken — you just don't know yet", "Type the boundaries: parameters and returns", "pyproject.toml is the single source of packaging truth"],
            },
            {
                t: "Performance and Profiling", s: "python-performance-profiling",
                e: "Make Python fast where it counts — measure first, then apply the optimizations that actually move the needle.",
                sec: [
                    ["Measure before optimizing", "Intuition about slowness is usually wrong. Time with timeit for snippets and cProfile for whole programs to find the real hot spot — then optimize only that. Premature optimization wastes effort on code that isn't the bottleneck.", 'import cProfile\ncProfile.run("main()")   # shows cumulative time per function'],
                    ["Choose the right data structure", "Algorithmic wins dwarf micro-tweaks: membership testing in a set is O(1) vs O(n) in a list; a dict lookup beats scanning. Turning an accidental O(n²) loop into O(n) with a set is often a 100× win no C rewrite can match.", 'seen = set(big_list)      # O(1) membership\nif target in seen: ...    # vs `in big_list` = O(n)'],
                    ["When Python isn't enough", "For numeric heavy lifting, NumPy vectorization runs C-speed loops. For CPU-bound parallelism, multiprocessing sidesteps the GIL. And caching (functools.lru_cache) turns repeated expensive calls into instant lookups — often the highest ROI line you'll write."],
                ],
                ex: "Write a function that finds duplicate values in a list of 100,000 items two ways — nested loops and a set — and use timeit to measure both. Report the speedup and explain the complexity difference.",
                tips: ["Profile to find the real bottleneck first", "The right data structure beats micro-optimization", "NumPy, multiprocessing, and lru_cache are the heavy hitters"],
            },
            {
                t: "Building a Real Project: CLI to API", s: "python-real-project",
                e: "Tie it all together — turn your code into a tool others can install and a service others can call.",
                sec: [
                    ["A polished CLI with argparse", "argparse turns a script into a proper command-line tool with arguments, flags, help text, and validation — the difference between a personal hack and something a teammate can use.", 'import argparse\np = argparse.ArgumentParser(description="Contact manager")\np.add_argument("name")\np.add_argument("--phone", required=True)\nargs = p.parse_args()\nprint(args.name, args.phone)'],
                    ["Exposing an API with FastAPI", "FastAPI turns typed functions into a documented HTTP API with automatic validation and interactive docs. Type hints drive request/response schemas — the payoff for learning typing earlier.", 'from fastapi import FastAPI\napp = FastAPI()\n\n@app.get("/greet/{name}")\ndef greet(name: str, formal: bool = False):\n    return {"message": f"{\'Good day\' if formal else \'Hi\'}, {name}"}'],
                    ["Shipping it", "Real delivery means: environment variables for config, logging instead of print, a requirements lockfile, tests in CI, and a container or host to run on. These habits turn 'works on my machine' into 'works in production'."],
                ],
                ex: "Build a URL-shortener: a FastAPI app with POST /shorten (returns a code) and GET /{code} (redirects), storing mappings in a dict, with type hints, three pytest tests against the app, and a README explaining how to run it.",
                tips: ["argparse makes scripts into real CLI tools", "FastAPI turns typed functions into documented APIs", "Config in env vars, logging over print, tests in CI"],
            },
            {
                t: "functools and itertools", s: "python-functools-itertools",
                e: "Two standard-library powerhouses for functional composition and efficient iteration.",
                sec: [
                    ["functools essentials", "functools offers reduce (fold an iterable to one value), partial (pre-fill some arguments of a function), lru_cache (memoize expensive calls in one line), and wraps (preserve metadata in decorators). lru_cache alone can turn a slow recursive function fast.", 'from functools import lru_cache, partial, reduce\n\n@lru_cache(maxsize=None)\ndef fib(n): return n if n < 2 else fib(n-1) + fib(n-2)\n\nadd = lambda a, b: a + b\nreduce(add, [1, 2, 3, 4])       # 10\ndouble = partial(add, 2)         # partial application'],
                    ["itertools for efficient loops", "itertools builds fast, memory-efficient iterators: chain (join iterables), islice (slice a stream), groupby, product/permutations/combinations, count/cycle/repeat (infinite), and accumulate (running totals). They compose into elegant data pipelines.", 'from itertools import chain, combinations, accumulate, count\nlist(chain([1, 2], [3, 4]))              # [1,2,3,4]\nlist(combinations("abc", 2))             # [(a,b),(a,c),(b,c)]\nlist(accumulate([1, 2, 3, 4]))           # [1,3,6,10]'],
                    ["Composing them", "Together these modules express complex logic concisely: memoize with lru_cache, generate combinations with itertools, and reduce results with functools — often replacing dozens of lines of manual loops while running faster.", 'from itertools import islice\nsquares = (n * n for n in count(1))       # infinite\nlist(islice(squares, 5))                  # first 5: [1,4,9,16,25]'],
                ],
                ex: "Speed up a naive recursive function with @lru_cache and measure the difference. Use itertools.combinations to generate all pairs from a list, accumulate for a running total, and reduce to multiply a list of numbers.",
                tips: ["functools: reduce, partial, lru_cache (free speed), wraps", "itertools: chain/islice/combinations/accumulate and infinite iterators", "Compose them to replace manual loops, faster and clearer"],
            },
            {
                t: "Properties and Descriptors", s: "python-descriptors-properties",
                e: "Control attribute access elegantly — computed values, validation, and reusable access logic.",
                sec: [
                    ["The @property decorator", "@property turns a method into a read-only attribute that runs logic on access — perfect for computed values that should look like plain attributes. Add a matching setter to validate on assignment.", 'class Circle:\n    def __init__(self, r): self._r = r\n    @property\n    def area(self): return 3.14159 * self._r ** 2\n    @property\n    def radius(self): return self._r\n    @radius.setter\n    def radius(self, v):\n        if v < 0: raise ValueError("radius must be >= 0")\n        self._r = v'],
                    ["Why not just public attributes?", "Start with plain attributes; add a property only when you need computation or validation — and the beauty is you can add it later without changing how callers use the attribute. This keeps APIs stable as requirements grow.", 'c = Circle(5)\nc.area          # looks like an attribute, runs a method\nc.radius = 10   # runs the setter\'s validation'],
                    ["Descriptors: reusable access logic", "A descriptor is a class implementing __get__/__set__ that manages attribute access across many classes — the mechanism behind property, ORM fields, and typed attributes. Write one when the same validation/access logic repeats on many attributes.", 'class Positive:\n    def __set_name__(self, owner, name): self.name = f"_{name}"\n    def __get__(self, obj, t): return getattr(obj, self.name)\n    def __set__(self, obj, v):\n        if v < 0: raise ValueError("must be positive")\n        setattr(obj, self.name, v)\nclass Product:\n    price = Positive()   # reusable validation'],
                ],
                ex: "Add a validated property to a class (e.g. a temperature that rejects values below absolute zero) with a getter and setter. Then write a reusable descriptor that enforces a non-empty string and apply it to two attributes.",
                tips: ["@property makes methods look like attributes (computed/validated)", "Add properties later without breaking callers", "Descriptors (__get__/__set__) reuse access logic across attributes"],
            },
            {
                t: "Async I/O with asyncio", s: "python-asyncio-deep",
                e: "Handle thousands of concurrent I/O operations on a single thread with async/await.",
                sec: [
                    ["Coroutines and the event loop", "An async def function is a coroutine that can pause at await points, letting the event loop run other coroutines meanwhile. This gives huge concurrency for I/O-bound work (network, disk) on one thread — without threads or their locking pitfalls.", 'import asyncio\nasync def fetch(n):\n    await asyncio.sleep(1)     # simulate I/O; yields control\n    return n * n\n\nasyncio.run(fetch(5))          # run a coroutine'],
                    ["Running work concurrently", "asyncio.gather runs many coroutines at once and collects results — turning sequential waits into parallel ones. Ten one-second fetches finish in about one second, not ten, because they overlap while awaiting.", 'async def main():\n    results = await asyncio.gather(*(fetch(i) for i in range(10)))\n    return results          # ~1s total, not 10s\nasyncio.run(main())'],
                    ["The rules and ecosystem", "async needs async all the way down — a blocking call (like time.sleep or a synchronous DB driver) stalls the whole loop. Use async libraries (aiohttp for HTTP, asyncpg for Postgres) and asyncio.to_thread to offload unavoidable blocking calls.", 'import aiohttp\nasync def get(url):\n    async with aiohttp.ClientSession() as s:\n        async with s.get(url) as r:\n            return await r.text()'],
                ],
                ex: "Write an async program that fetches (simulated with asyncio.sleep) ten resources concurrently with gather and times it against a sequential version. Explain why a synchronous time.sleep inside a coroutine would break the concurrency.",
                tips: ["async def coroutines pause at await; the loop runs others", "asyncio.gather overlaps I/O — huge concurrency on one thread", "Async all the way down; offload blocking calls to threads"],
            },
            {
                t: "Advanced Type Hints", s: "python-typing-advanced",
                e: "Go beyond basic annotations to make large Python codebases safe and self-documenting.",
                sec: [
                    ["Generics and TypeVar", "Type variables let you write generic functions and classes that preserve types. A function annotated with TypeVar T returning T tells the checker the output matches the input type, catching mismatches without losing flexibility.", 'from typing import TypeVar\nT = TypeVar("T")\ndef first(items: list[T]) -> T | None:\n    return items[0] if items else None\nn = first([1, 2, 3])      # inferred as int | None'],
                    ["Protocols and structural typing", "Protocol defines an interface by shape, not inheritance — any object with the right methods satisfies it (static duck typing). This types Python's flexible duck-typing style so the checker can verify it.", 'from typing import Protocol\nclass Comparable(Protocol):\n    def __lt__(self, other) -> bool: ...\ndef smallest(items: list[Comparable]): return min(items)'],
                    ["TypedDict, Literal, and more", "TypedDict types dict shapes (common for JSON), Literal restricts to specific values, and Optional/Union model alternatives. Run mypy or pyright to actually enforce these — annotations are only checked by tools, not at runtime.", 'from typing import TypedDict, Literal\nclass User(TypedDict):\n    id: int\n    name: str\nStatus = Literal["active", "inactive"]\ndef set_status(s: Status) -> None: ...'],
                ],
                ex: "Write a generic function with TypeVar that filters and returns the same list type. Define a Protocol for objects with a .area() method and a function that works on any of them. Type a JSON-shaped dict with TypedDict and check it with mypy.",
                tips: ["TypeVar/Generics preserve types through functions and classes", "Protocol types duck typing by shape, not inheritance", "TypedDict/Literal refine dicts and values; enforce with mypy"],
            },
            {
                t: "Databases with sqlite3 and the DB-API", s: "python-databases",
                e: "Persist data in a real database using Python's built-in database interface.",
                sec: [
                    ["SQLite comes built in", "The sqlite3 module gives you a full SQL database with zero setup — a single file (or in-memory). Connect, get a cursor, execute SQL, and commit. It's perfect for scripts, tests, and small apps, and teaches the DB-API used by every Python database.", 'import sqlite3\nconn = sqlite3.connect("app.db")\ncur = conn.cursor()\ncur.execute("CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, name TEXT)")\nconn.commit()'],
                    ["Parameterized queries", "Never build SQL by concatenating values — that invites SQL injection. Use placeholders (?) and pass values separately; the driver escapes them safely. This is the single most important database security habit.", 'cur.execute("INSERT INTO users (name) VALUES (?)", ("Asha",))\ncur.execute("SELECT * FROM users WHERE name = ?", (name,))\nrows = cur.fetchall()\nconn.commit()'],
                    ["Transactions and beyond", "Group related writes in a transaction so they all succeed or all roll back on error. Use `with conn:` for automatic commit/rollback. For other databases the DB-API is the same shape — swap sqlite3 for psycopg (Postgres) or use an ORM like SQLAlchemy for larger apps.", 'with conn:                      # auto commit / rollback\n    conn.execute("UPDATE accounts SET bal = bal - 100 WHERE id = 1")\n    conn.execute("UPDATE accounts SET bal = bal + 100 WHERE id = 2")'],
                ],
                ex: "Build a small SQLite-backed contact book: create a table, insert several contacts with parameterized queries, query by name safely, and wrap a multi-step update in a transaction. Confirm data persists across runs.",
                tips: ["sqlite3 is a full SQL database built in, zero setup", "Always use ? placeholders — never concatenate SQL (injection)", "Group writes in transactions (with conn:); DB-API is portable"],
            },
            {
                t: "HTTP Requests and Web Scraping", s: "python-web-requests",
                e: "Fetch data from the web and extract information from pages responsibly.",
                sec: [
                    ["Making HTTP requests", "The requests library (the de-facto standard) makes HTTP simple: get/post with params, headers, and JSON bodies, and read the response as .json() or .text. Always check status_code and handle timeouts and errors.", 'import requests\nr = requests.get("https://api.github.com/users/torvalds", timeout=10)\nr.raise_for_status()          # raise on 4xx/5xx\ndata = r.json()\nprint(data["name"])'],
                    ["Sending data and headers", "POST JSON with the json= argument, add authentication via headers, and pass query parameters with params. Sessions reuse connections and cookies across requests for efficiency and stateful APIs.", 'requests.post("https://api.example.com/items",\n              json={"name": "New"},\n              headers={"Authorization": f"Bearer {token}"})'],
                    ["Parsing HTML responsibly", "For pages without an API, BeautifulSoup parses HTML so you can extract elements by tag, class, or CSS selector. Scrape responsibly: respect robots.txt and terms of service, rate-limit your requests, prefer official APIs, and never overload a site.", 'from bs4 import BeautifulSoup\nsoup = BeautifulSoup(r.text, "html.parser")\ntitle = soup.select_one("h1").text\nlinks = [a["href"] for a in soup.select("a[href]")]'],
                ],
                ex: "Use requests to fetch JSON from a public API and print a few fields, handling errors with raise_for_status and a timeout. Then fetch an HTML page and use BeautifulSoup to extract all the headings — noting the ethical scraping rules.",
                tips: ["requests: get/post with params/json/headers; check status", "Use a Session for connection reuse and cookies", "BeautifulSoup parses HTML — scrape ethically, prefer APIs"],
            },
            {
                t: "Idiomatic Python and Best Practices", s: "python-best-practices",
                e: "Write Python the way experienced developers do — clean, readable, and Pythonic.",
                sec: [
                    ["PEP 8 and readability", "PEP 8 is the style guide: 4-space indents, snake_case names, spaces around operators, and lines under ~79–99 chars. Consistency matters more than any single rule — use a formatter (black) and linter (ruff) to enforce it automatically, so you never argue about style.", '# tools do this for you:\n#   black .     -> formats\n#   ruff check  -> lints for bugs and style'],
                    ["Pythonic idioms", "Prefer Python's expressive patterns: comprehensions over manual loops, enumerate instead of range(len()), zip to iterate in parallel, unpacking, truthiness (`if items:`), context managers for resources, and EAFP ('easier to ask forgiveness') — try/except over pre-checking.", 'for i, item in enumerate(items): ...        # not range(len())\nfor name, score in zip(names, scores): ...  # parallel\nif not results: ...                          # truthiness\ntry: value = data[key]\nexcept KeyError: value = default             # EAFP'],
                    ["Common pitfalls", "Avoid the classic traps: mutable default arguments, modifying a list while iterating it, confusing is with ==, deep nesting (use early returns/guard clauses), and catching bare exceptions that hide bugs. Small pure functions, clear names, and tests keep code maintainable as it grows."],
                ],
                ex: "Take a piece of un-Pythonic code (range(len()) loops, manual index counters, pre-checking keys, a bare except) and refactor it applying enumerate, zip, comprehensions, EAFP, and specific exceptions. Run black and ruff on the result.",
                tips: ["Follow PEP 8; enforce with black + ruff automatically", "Pythonic: comprehensions, enumerate/zip, truthiness, EAFP", "Avoid mutable defaults, bare except, and mutating while iterating"],
            },
        ],
    },
}
